{"seeAlsoSections":[{"title":"Behaviors","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelDefaultBehavior"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBehavior"}],"title":"FloatingPanelBehavior","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelBehavior","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelBehavior"}]},"abstract":[{"type":"text","text":"An interface for generating behavior information to fine-tune the behavior of a panel."}],"sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelDefaultBehavior"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/momentumProjectionRate","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/removalInteractionVelocityThreshold","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/springDecelerationRate","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/springResponseTime"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/allowsRubberBanding(for:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/redirectionalProgress(_:from:to:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/shouldProjectMomentum(_:to:)"]}],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBehavior"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/springDecelerationRate":{"role":"symbol","title":"springDecelerationRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"springDecelerationRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A floating-point value that determines the rate of oscillation magnitude reduction after the user lifts their finger."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/springDecelerationRate","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/springdecelerationrate"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/redirectionalProgress(_:from:to:)":{"role":"symbol","title":"redirectionalProgress(_:from:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectionalProgress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"Returns the progress to redirect to the previous position."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/redirectionalProgress(_:from:to:)","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/redirectionalprogress(_:from:to:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/allowsRubberBanding(for:)":{"role":"symbol","title":"allowsRubberBanding(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsRubberBanding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIRectEdge","preciseIdentifier":"c:@E@UIRectEdge"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Asks the behavior whether the rubber band effect is enabled in moving over a given edge of the surface view."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/allowsRubberBanding(for:)","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/allowsrubberbanding(for:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/shouldProjectMomentum(_:to:)":{"role":"symbol","title":"shouldProjectMomentum(_:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldProjectMomentum"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Asks the behavior if a panel should project a momentum of a user interaction to move the proposed position."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/shouldProjectMomentum(_:to:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/shouldprojectmomentum(_:to:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/springResponseTime":{"role":"symbol","title":"springResponseTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"springResponseTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A floating-point value that determines the approximate time until a panel stops to an anchor after the user lifts their finger."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/springResponseTime","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/springresponsetime"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/removalInteractionVelocityThreshold":{"role":"symbol","title":"removalInteractionVelocityThreshold","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"removalInteractionVelocityThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"Returns the velocity threshold for the default interactive removal gesture."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/removalInteractionVelocityThreshold","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/removalinteractionvelocitythreshold"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior":{"role":"symbol","title":"FloatingPanelBehavior","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBehavior"}],"abstract":[{"type":"text","text":"An interface for generating behavior information to fine-tune the behavior of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelBehavior"}],"url":"\/documentation\/floatingpanel\/floatingpanelbehavior"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelDefaultBehavior":{"role":"symbol","title":"FloatingPanelDefaultBehavior","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelDefaultBehavior"}],"abstract":[{"type":"text","text":"The default behavior object for a panel"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelDefaultBehavior","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelDefaultBehavior"}],"url":"\/documentation\/floatingpanel\/floatingpaneldefaultbehavior"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"The new interface displays the related contents and utilities in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/momentumProjectionRate":{"role":"symbol","title":"momentumProjectionRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"momentumProjectionRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"Returns a deceleration rate to calculate a target position projected a dragging momentum."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/momentumProjectionRate","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/momentumprojectionrate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBehavior"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}