{"abstract":[{"text":"Returns the layout anchors to specify the snapping locations for each state.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"anchors","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","text":"FloatingPanelState","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayoutAnchoring","kind":"typeIdentifier","text":"FloatingPanelLayoutAnchoring","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"anchors"}],"required":true,"modules":[{"name":"FloatingPanel"}],"title":"anchors","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout(py)anchors","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchors","kind":"identifier"},{"text":": [","kind":"text"},{"text":"FloatingPanelState","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayoutAnchoring","text":"FloatingPanelLayoutAnchoring","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout\/anchors","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanellayout\/anchors"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanellayout\/anchors"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayout":{"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayout","abstract":[{"type":"text","text":"An interface for generating layout information for a panel."}],"title":"FloatingPanelLayout","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FloatingPanelLayout","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayout"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelState":{"url":"\/documentation\/floatingpanel\/floatingpanelstate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelState","kind":"identifier"}],"title":"FloatingPanelState","abstract":[{"type":"text","text":"An object that represents the display state of a panel in a screen."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","role":"symbol","type":"topic","navigatorTitle":[{"text":"FloatingPanelState","kind":"identifier"}],"kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchoring":{"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchoring","type":"topic","abstract":[{"text":"An interface for implementing custom layout anchor objects.","type":"text"}],"title":"FloatingPanelLayoutAnchoring","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FloatingPanelLayoutAnchoring","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayout/anchors":{"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayout\/anchors","required":true,"abstract":[{"type":"text","text":"Returns the layout anchors to specify the snapping locations for each state."}],"title":"anchors","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout\/anchors","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"anchors","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchors"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"FloatingPanelLayoutAnchoring","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayoutAnchoring"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"anchors","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"anchors"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<FloatingPanelState *,id<FloatingPanelLayoutAnchoring>>"},{"text":" * ","kind":"text"},{"text":"anchors","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/title","value":"FloatingPanelLayout","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayout"}],"op":"replace"},{"op":"replace","value":"FloatingPanelState","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/fragments","op":"replace","value":[{"text":"FloatingPanelState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring\/title","op":"replace","value":"FloatingPanelLayoutAnchoring"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring\/fragments","value":[{"text":"FloatingPanelLayoutAnchoring","kind":"identifier"}]},{"value":"anchors","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout~1anchors\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout~1anchors\/fragments","value":[{"kind":"identifier","text":"anchors"}],"op":"replace"}]}]}