{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideNone"}],"role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide.none","symbolKind":"case","modules":[{"name":"FloatingPanel"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"externalID":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide@FloatingPanelLayoutContentBoundingGuideNone"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/none","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/none"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide","abstract":[{"text":"A representation to specify a bounding box which limit the content size of a panel.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","title":"FloatingPanelLayoutContentBoundingGuide","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide/none":{"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/none","role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide.none","abstract":[],"kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideNone"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"FloatingPanelLayoutContentBoundingGuideNone","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideNone"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"FloatingPanelLayoutContentBoundingGuideNone","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"FloatingPanelLayoutContentBoundingGuide","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/title"},{"value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1none\/title","op":"replace","value":"FloatingPanelLayoutContentBoundingGuideNone"},{"value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideNone"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1none\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}