{"sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/safeArea","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","modules":[{"name":"FloatingPanel"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"safeArea","kind":"identifier"}],"externalID":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide@FloatingPanelLayoutContentBoundingGuideSafeArea","symbolKind":"case","navigatorTitle":[{"text":"FloatingPanelLayoutContentBoundingGuideSafeArea","kind":"identifier"}],"title":"FloatingPanelLayoutContentBoundingGuide.safeArea"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"safeArea","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide"]]},"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/safearea"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/safearea"]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide","abstract":[{"text":"A representation to specify a bounding box which limit the content size of a panel.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","title":"FloatingPanelLayoutContentBoundingGuide","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide/safeArea":{"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/safeArea","role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide.safeArea","abstract":[],"kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/safearea","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"safeArea","kind":"identifier"}],"navigatorTitle":[{"text":"FloatingPanelLayoutContentBoundingGuideSafeArea","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelLayoutContentBoundingGuideSafeArea"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"FloatingPanelLayoutContentBoundingGuideSafeArea","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"FloatingPanelLayoutContentBoundingGuideSafeArea","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/title","value":"FloatingPanelLayoutContentBoundingGuide"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/fragments","op":"replace","value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}]},{"value":"FloatingPanelLayoutContentBoundingGuideSafeArea","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1safeArea\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1safeArea\/fragments","op":"replace","value":[{"text":"FloatingPanelLayoutContentBoundingGuideSafeArea","kind":"identifier"}]}]}]}