{"seeAlsoSections":[{"title":"Views","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackdropView"}],"title":"BackdropView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelBackdropView","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"BackdropView"}]},"abstract":[{"type":"text","text":"A view that presents a backdrop interface behind a panel."}],"sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/BackdropView","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSCoding","doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject","doc:\/\/com.scenee.FloatingPanel\/objc(pl)CALayerDelegate","doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP","doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/SQ","doc:\/\/com.scenee.FloatingPanel\/SH","doc:\/\/com.scenee.FloatingPanel\/s8SendableP","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearance","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearanceContainer","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UICoordinateSpace","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIDynamicItem","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusEnvironment","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusItem","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusItemContainer","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UILargeContentViewerItem","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.scenee.FloatingPanel\/5UIKit23UITraitChangeObservableP","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UITraitEnvironment","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/BackdropView\/dismissalTapGestureRecognizer"]}],"variants":[{"paths":["\/documentation\/floatingpanel\/backdropview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/backdropview"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FloatingPanelBackdropView) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackdropView"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.scenee.FloatingPanel/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusEnvironment"},"doc://com.scenee.FloatingPanel/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIUserActivityRestoring"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIDynamicItem"},"doc://com.scenee.FloatingPanel/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusItem"},"doc://com.scenee.FloatingPanel/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.scenee.FloatingPanel/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)CALayerDelegate"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBackdropView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBackdropView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/floatingpanel\/floatingpanelbackdropview\/initwithcoder:"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/BackdropView":{"role":"symbol","title":"BackdropView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackdropView"}],"abstract":[{"type":"text","text":"A view that presents a backdrop interface behind a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/BackdropView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BackdropView"}],"url":"\/documentation\/floatingpanel\/backdropview"},"doc://com.scenee.FloatingPanel/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP"},"doc://com.scenee.FloatingPanel/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/GrabberView":{"role":"symbol","title":"GrabberView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GrabberView"}],"abstract":[{"type":"text","text":"A view that presents a grabber handle in the surface of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GrabberView"}],"url":"\/documentation\/floatingpanel\/grabberview"},"doc://com.scenee.FloatingPanel/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearanceContainer"},"doc://com.scenee.FloatingPanel/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UITraitEnvironment"},"doc://com.scenee.FloatingPanel/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusItemContainer"},"doc://com.scenee.FloatingPanel/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAccessibilityIdentification"},"doc://com.scenee.FloatingPanel/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceAppearance":{"role":"symbol","title":"SurfaceAppearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurfaceAppearance"}],"abstract":[{"type":"text","text":"An object for customizing the appearance of a surface view"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SurfaceAppearance"}],"url":"\/documentation\/floatingpanel\/surfaceappearance"},"doc://com.scenee.FloatingPanel/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UICoordinateSpace"},"doc://com.scenee.FloatingPanel/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBackdropView/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBackdropView\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/floatingpanel\/floatingpanelbackdropview\/init"},"doc://com.scenee.FloatingPanel/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIView"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/BackdropView/dismissalTapGestureRecognizer":{"role":"symbol","title":"dismissalTapGestureRecognizer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissalTapGestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"}],"abstract":[{"type":"text","text":"The gesture recognizer for tap gestures to dismiss a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/BackdropView\/dismissalTapGestureRecognizer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissalTapGestureRecognizer"}],"url":"\/documentation\/floatingpanel\/backdropview\/dismissaltapgesturerecognizer"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView":{"role":"symbol","title":"SurfaceView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurfaceView"}],"abstract":[{"type":"text","text":"A view that presents a surface interface in a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SurfaceView"}],"url":"\/documentation\/floatingpanel\/surfaceview"},"doc://com.scenee.FloatingPanel/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.scenee.FloatingPanel\/5UIKit23UITraitChangeObservableP"},"doc://com.scenee.FloatingPanel/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSCoding"},"doc://com.scenee.FloatingPanel/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.scenee.FloatingPanel\/s8SendableP"},"doc://com.scenee.FloatingPanel/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SH"},"doc://com.scenee.FloatingPanel/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.scenee.FloatingPanel/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP"},"doc://com.scenee.FloatingPanel/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearance"},"doc://com.scenee.FloatingPanel/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SQ"},"doc://com.scenee.FloatingPanel/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIResponderStandardEditActions"},"doc://com.scenee.FloatingPanel/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UILargeContentViewerItem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelBackdropView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FloatingPanelBackdropView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FloatingPanelBackdropView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/BackdropView\/dismissalTapGestureRecognizer"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBackdropView\/init","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBackdropView\/initWithCoder:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Views","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBackdropView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1BackdropView\/title","value":"FloatingPanelBackdropView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1BackdropView\/fragments","value":[{"kind":"identifier","text":"FloatingPanelBackdropView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView\/title","value":"FloatingPanelGrabberView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView\/fragments","value":[{"kind":"identifier","text":"FloatingPanelGrabberView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceAppearance\/title","value":"FloatingPanelSurfaceAppearance"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceAppearance\/fragments","value":[{"kind":"identifier","text":"FloatingPanelSurfaceAppearance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1BackdropView~1dismissalTapGestureRecognizer\/title","value":"dismissalTapGestureRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1BackdropView~1dismissalTapGestureRecognizer\/fragments","value":[{"kind":"identifier","text":"dismissalTapGestureRecognizer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/title","value":"FloatingPanelSurfaceView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/fragments","value":[{"kind":"identifier","text":"FloatingPanelSurfaceView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}