{"seeAlsoSections":[{"title":"Views","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/BackdropView"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GrabberView"}],"title":"GrabberView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelGrabberView","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"GrabberView"}]},"abstract":[{"type":"text","text":"A view that presents a grabber handle in the surface of a panel."}],"sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSCoding","doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject","doc:\/\/com.scenee.FloatingPanel\/objc(pl)CALayerDelegate","doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP","doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/SQ","doc:\/\/com.scenee.FloatingPanel\/SH","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearance","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearanceContainer","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UICoordinateSpace","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIDynamicItem","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusEnvironment","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusItem","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusItemContainer","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UILargeContentViewerItem","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.scenee.FloatingPanel\/5UIKit23UITraitChangeObservableP","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UITraitEnvironment","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/barColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/hitTest(_:with:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/layoutSubviews()"]}],"variants":[{"paths":["\/documentation\/floatingpanel\/grabberview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/grabberview"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(FloatingPanelGrabberView) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GrabberView"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.scenee.FloatingPanel/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.scenee.FloatingPanel/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.scenee.FloatingPanel/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIUserActivityRestoring"},"doc://com.scenee.FloatingPanel/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIDynamicItem"},"doc://com.scenee.FloatingPanel/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP"},"doc://com.scenee.FloatingPanel/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIView"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/GrabberView":{"role":"symbol","title":"GrabberView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GrabberView"}],"abstract":[{"type":"text","text":"A view that presents a grabber handle in the surface of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GrabberView"}],"url":"\/documentation\/floatingpanel\/grabberview"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/GrabberView/barColor":{"role":"symbol","title":"barColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/barColor","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/grabberview\/barcolor"},"doc://com.scenee.FloatingPanel/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SH"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/GrabberView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/floatingpanel\/grabberview\/init(coder:)"},"doc://com.scenee.FloatingPanel/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject"},"doc://com.scenee.FloatingPanel/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UITraitEnvironment"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView":{"role":"symbol","title":"SurfaceView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurfaceView"}],"abstract":[{"type":"text","text":"A view that presents a surface interface in a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SurfaceView"}],"url":"\/documentation\/floatingpanel\/surfaceview"},"doc://com.scenee.FloatingPanel/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)CALayerDelegate"},"doc://com.scenee.FloatingPanel/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SQ"},"doc://com.scenee.FloatingPanel/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UILargeContentViewerItem"},"doc://com.scenee.FloatingPanel/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusEnvironment"},"doc://com.scenee.FloatingPanel/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UICoordinateSpace"},"doc://com.scenee.FloatingPanel/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIResponderStandardEditActions"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/GrabberView/hitTest(_:with:)":{"role":"symbol","title":"hitTest(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hitTest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/hitTest(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hitTest:withEvent:"}],"url":"\/documentation\/floatingpanel\/grabberview\/hittest(_:with:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceAppearance":{"role":"symbol","title":"SurfaceAppearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurfaceAppearance"}],"abstract":[{"type":"text","text":"An object for customizing the appearance of a surface view"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SurfaceAppearance"}],"url":"\/documentation\/floatingpanel\/surfaceappearance"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/BackdropView":{"role":"symbol","title":"BackdropView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackdropView"}],"abstract":[{"type":"text","text":"A view that presents a backdrop interface behind a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/BackdropView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BackdropView"}],"url":"\/documentation\/floatingpanel\/backdropview"},"doc://com.scenee.FloatingPanel/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearance"},"doc://com.scenee.FloatingPanel/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.scenee.FloatingPanel\/5UIKit23UITraitChangeObservableP"},"doc://com.scenee.FloatingPanel/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSCoding"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelGrabberView/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelGrabberView\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/floatingpanel\/floatingpanelgrabberview\/init"},"doc://com.scenee.FloatingPanel/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP"},"doc://com.scenee.FloatingPanel/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearanceContainer"},"doc://com.scenee.FloatingPanel/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/GrabberView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/floatingpanel\/grabberview\/layoutsubviews()"},"doc://com.scenee.FloatingPanel/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusItemContainer"},"doc://com.scenee.FloatingPanel/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusItem"},"doc://com.scenee.FloatingPanel/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAccessibilityIdentification"},"doc://com.scenee.FloatingPanel/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelGrabberView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FloatingPanelGrabberView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FloatingPanelGrabberView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelGrabberView\/init","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/hitTest(_:with:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/init(coder:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Views","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/BackdropView"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelGrabberView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView\/title","value":"FloatingPanelGrabberView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView\/fragments","value":[{"kind":"identifier","text":"FloatingPanelGrabberView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/title","value":"FloatingPanelSurfaceView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/fragments","value":[{"kind":"identifier","text":"FloatingPanelSurfaceView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView~1hitTest(_:with:)\/title","value":"hitTest:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView~1hitTest(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hitTest:withEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceAppearance\/title","value":"FloatingPanelSurfaceAppearance"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceAppearance\/fragments","value":[{"kind":"identifier","text":"FloatingPanelSurfaceAppearance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1BackdropView\/title","value":"FloatingPanelBackdropView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1BackdropView\/fragments","value":[{"kind":"identifier","text":"FloatingPanelBackdropView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1GrabberView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}