{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelControllerDelegate","kind":"identifier"}],"modules":[{"name":"FloatingPanel"}],"title":"FloatingPanelControllerDelegate","symbolKind":"protocol","role":"symbol","roleHeading":"Protocol"},"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:animatorForDismissingWith:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:animatorForPresentingTo:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:contentOffsetForPinning:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:layoutFor:)-7vm4h","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:layoutFor:)-953xh","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:shouldAllowToScroll:in:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:shouldRemoveAt:with:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidChangeState(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidEndAttracting(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidEndDragging(_:willAttract:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidMove(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidRemove(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelShouldBeginDragging(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillBeginAttracting(_:to:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillBeginDragging(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillEndDragging(_:withVelocity:targetState:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillRemove(_:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel"]]},"abstract":[{"type":"text","text":"A set of methods implemented by the delegate of a panel controller allows the adopting delegate to respond to"},{"type":"text","text":" "},{"type":"text","text":"messages from the FloatingPanelController class and thus respond to, and in some affect, operations such as"},{"text":" ","type":"text"},{"text":"dragging, attracting a panel, layout of a panel and the content, and transition animations.","type":"text"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"],"title":"Essentials"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelControllerDelegate","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelShouldBeginDragging(_:)":{"title":"floatingPanelShouldBeginDragging(_:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelShouldBeginDragging(_:)","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelshouldbegindragging(_:)","abstract":[{"type":"text","text":"Asks the delegate if dragging should begin by the pan gesture recognizer."}],"navigatorTitle":[{"kind":"identifier","text":"floatingPanelShouldBeginDragging:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"floatingPanelShouldBeginDragging","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:shouldRemoveAt:with:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:shouldRemoveAt:with:)","abstract":[{"text":"Asks the delegate whether a panel should be removed when dragging ended at the specified location","type":"text"}],"navigatorTitle":[{"text":"floatingPanel:shouldRemoveAtLocation:withVelocity:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanel"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldRemoveAt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGVector","kind":"typeIdentifier","text":"CGVector"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"floatingPanel(_:shouldRemoveAt:with:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:shouldremoveat:with:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:animatorForPresentingTo:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:animatorForPresentingTo:)","abstract":[{"text":"Returns a UIViewPropertyAnimator object to add\/present the  panel to a position.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"floatingPanel:animatorForPresentingToState:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"floatingPanel"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"animatorForPresentingTo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewPropertyAnimator","preciseIdentifier":"c:objc(cs)UIViewPropertyAnimator","kind":"typeIdentifier"}],"type":"topic","required":true,"title":"floatingPanel(_:animatorForPresentingTo:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:animatorforpresentingto:)","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelDidChangeState(_:)":{"title":"floatingPanelDidChangeState(_:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpaneldidchangestate(_:)","navigatorTitle":[{"text":"floatingPanelDidChangeState:","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidChangeState(_:)","abstract":[{"type":"text","text":"Called when a panel has changed to a new state."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"floatingPanelDidChangeState","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelWillBeginAttracting(_:to:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillBeginAttracting(_:to:)","abstract":[{"type":"text","text":"Called when it is about to be attracted to a state anchor."}],"navigatorTitle":[{"kind":"identifier","text":"floatingPanelWillBeginAttracting:to:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"floatingPanelWillBeginAttracting","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","kind":"typeIdentifier","text":"FloatingPanelState"},{"text":")","kind":"text"}],"type":"topic","title":"floatingPanelWillBeginAttracting(_:to:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillbeginattracting(_:to:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:layoutFor:)-953xh":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:layoutFor:)-953xh","abstract":[{"type":"text","text":"Returns a FloatingPanelLayout object. If you use the default one, you can use a "},{"code":"FloatingPanelBottomLayout","type":"codeVoice"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"floatingPanel:layoutForSize:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanel"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layoutFor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"FloatingPanelLayout","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout","kind":"typeIdentifier"}],"type":"topic","title":"floatingPanel(_:layoutFor:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:layoutfor:)-953xh","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"abstract":[{"text":"A set of methods implemented by the delegate of a panel controller allows the adopting delegate to respond to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"messages from the FloatingPanelController class and thus respond to, and in some affect, operations such as"},{"type":"text","text":" "},{"type":"text","text":"dragging, attracting a panel, layout of a panel and the content, and transition animations."}],"title":"FloatingPanelControllerDelegate","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelControllerDelegate","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelWillRemove(_:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillRemove(_:)","abstract":[{"text":"Called on start to remove its view controller from the parent view controller.","type":"text"}],"navigatorTitle":[{"text":"floatingPanelWillRemove:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanelWillRemove"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","required":true,"title":"floatingPanelWillRemove(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillremove(_:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:contentOffsetForPinning:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:contentOffsetForPinning:)","abstract":[{"type":"text","text":"Asks the delegate for a content offset of the tracking scroll view to be pinned when a panel moves"}],"navigatorTitle":[{"kind":"identifier","text":"floatingPanel:contentOffsetForPinningScrollView:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanel"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":", ","kind":"text"},{"text":"contentOffsetForPinning","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"type":"topic","title":"floatingPanel(_:contentOffsetForPinning:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:contentoffsetforpinning:)","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:animatorForDismissingWith:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:animatorForDismissingWith:)","abstract":[{"text":"Returns a UIViewPropertyAnimator object to remove\/dismiss a panel from a position.","type":"text"}],"navigatorTitle":[{"text":"floatingPanel:animatorForDismissingWithVelocity:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanel"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":", ","kind":"text"},{"text":"animatorForDismissingWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGVector","text":"CGVector","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewPropertyAnimator","text":"UIViewPropertyAnimator"}],"type":"topic","required":true,"title":"floatingPanel(_:animatorForDismissingWith:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:animatorfordismissingwith:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:layoutFor:)-7vm4h":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:layoutFor:)-7vm4h","abstract":[{"type":"text","text":"Returns a FloatingPanelLayout object. If you use the default one, you can use a "},{"type":"codeVoice","code":"FloatingPanelBottomLayout"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"floatingPanel:layoutForTraitCollection:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"floatingPanel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"layoutFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout","kind":"typeIdentifier","text":"FloatingPanelLayout"}],"type":"topic","title":"floatingPanel(_:layoutFor:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:layoutfor:)-7vm4h","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelWillEndDragging(_:withVelocity:targetState:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"floatingPanelWillEndDragging","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":", "},{"text":"withVelocity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"targetState","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","kind":"typeIdentifier","text":"FloatingPanelState"},{"text":">)","kind":"text"}],"navigatorTitle":[{"text":"floatingPanelWillEndDragging:withVelocity:targetState:","kind":"identifier"}],"type":"topic","title":"floatingPanelWillEndDragging(_:withVelocity:targetState:)","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillenddragging(_:withvelocity:targetstate:)","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillEndDragging(_:withVelocity:targetState:)","abstract":[{"text":"Called on finger up if the user dragged. velocity is in points\/second.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelDidMove(_:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidMove(_:)","abstract":[{"text":"Called while the user drags the surface or the surface moves to a state anchor.","type":"text"}],"navigatorTitle":[{"text":"floatingPanelDidMove:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"floatingPanelDidMove","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":")","kind":"text"}],"type":"topic","required":true,"title":"floatingPanelDidMove(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpaneldidmove(_:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelDidEndDragging(_:willAttract:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidEndDragging(_:willAttract:)","abstract":[{"text":"Called on finger up if the user dragged.","type":"text"}],"navigatorTitle":[{"text":"floatingPanelDidEndDragging:willAttract:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"floatingPanelDidEndDragging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willAttract"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"floatingPanelDidEndDragging(_:willAttract:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpaneldidenddragging(_:willattract:)","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelWillBeginDragging(_:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillBeginDragging(_:)","abstract":[{"type":"text","text":"Called on start of dragging (may require some time and or distance to move)"}],"navigatorTitle":[{"text":"floatingPanelWillBeginDragging:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanelWillBeginDragging"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":")","kind":"text"}],"type":"topic","required":true,"title":"floatingPanelWillBeginDragging(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillbegindragging(_:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:shouldAllowToScroll:in:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:shouldAllowToScroll:in:)","abstract":[{"type":"text","text":"Returns a Boolean value that determines whether the tracking scroll view should"},{"text":" ","type":"text"},{"text":"scroll or not","type":"text"}],"navigatorTitle":[{"text":"floatingPanel:shouldAllowToScroll:in:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"floatingPanel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","kind":"typeIdentifier","text":"FloatingPanelController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldAllowToScroll"},{"text":": ","kind":"text"},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FloatingPanelState","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","required":true,"title":"floatingPanel(_:shouldAllowToScroll:in:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:shouldallowtoscroll:in:)","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelDidRemove(_:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidRemove(_:)","abstract":[{"type":"text","text":"Called when a panel is removed from the parent view controller."}],"navigatorTitle":[{"text":"floatingPanelDidRemove:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanelDidRemove"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"floatingPanelDidRemove(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpaneldidremove(_:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelDidEndAttracting(_:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidEndAttracting(_:)","abstract":[{"text":"Called when attracting it is completed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"floatingPanelDidEndAttracting:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanelDidEndAttracting"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","required":true,"title":"floatingPanelDidEndAttracting(_:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpaneldidendattracting(_:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelControllerDelegate"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"FloatingPanelControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"FloatingPanelControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:animatorForDismissingWith:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:animatorForPresentingTo:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:contentOffsetForPinning:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:layoutFor:)-7vm4h","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:layoutFor:)-953xh","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:shouldAllowToScroll:in:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:shouldRemoveAt:with:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidChangeState(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidEndAttracting(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidEndDragging(_:willAttract:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidMove(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelDidRemove(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelShouldBeginDragging(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillBeginAttracting(_:to:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillBeginDragging(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillEndDragging(_:withVelocity:targetState:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillRemove(_:)"]}],"op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"],"title":"Essentials","generated":true}]},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"FloatingPanelControllerDelegate","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelShouldBeginDragging(_:)\/title","value":"floatingPanelShouldBeginDragging:"},{"value":[{"kind":"text","text":"- "},{"text":"floatingPanelShouldBeginDragging:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelShouldBeginDragging(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:shouldRemoveAt:with:)\/title","value":"floatingPanel:shouldRemoveAtLocation:withVelocity:","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:shouldRemoveAt:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"floatingPanel:shouldRemoveAtLocation:withVelocity:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","op":"replace","value":"FloatingPanelController"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"text":"FloatingPanelController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:animatorForPresentingTo:)\/title","value":"floatingPanel:animatorForPresentingToState:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"floatingPanel:animatorForPresentingToState:"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:animatorForPresentingTo:)\/fragments","op":"replace"},{"value":"floatingPanelDidChangeState:","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidChangeState(_:)\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidChangeState(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"floatingPanelDidChangeState:","kind":"identifier"}]},{"value":"floatingPanelWillBeginAttracting:to:","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillBeginAttracting(_:to:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"floatingPanelWillBeginAttracting:to:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillBeginAttracting(_:to:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:layoutFor:)-953xh\/title","value":"floatingPanel:layoutForSize:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"floatingPanel:layoutForSize:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:layoutFor:)-953xh\/fragments"},{"value":"FloatingPanelControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillRemove(_:)\/title","value":"floatingPanelWillRemove:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillRemove(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floatingPanelWillRemove:"}]},{"op":"replace","value":"floatingPanel:contentOffsetForPinningScrollView:","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:contentOffsetForPinning:)\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:contentOffsetForPinning:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"floatingPanel:contentOffsetForPinningScrollView:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:animatorForDismissingWith:)\/title","op":"replace","value":"floatingPanel:animatorForDismissingWithVelocity:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"floatingPanel:animatorForDismissingWithVelocity:"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:animatorForDismissingWith:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:layoutFor:)-7vm4h\/title","value":"floatingPanel:layoutForTraitCollection:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"floatingPanel:layoutForTraitCollection:"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:layoutFor:)-7vm4h\/fragments"},{"op":"replace","value":"floatingPanelWillEndDragging:withVelocity:targetState:","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillEndDragging(_:withVelocity:targetState:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"floatingPanelWillEndDragging:withVelocity:targetState:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillEndDragging(_:withVelocity:targetState:)\/fragments"},{"value":"floatingPanelDidMove:","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidMove(_:)\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidMove(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"floatingPanelDidMove:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidEndDragging(_:willAttract:)\/title","value":"floatingPanelDidEndDragging:willAttract:","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidEndDragging(_:willAttract:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"floatingPanelDidEndDragging:willAttract:","kind":"identifier"}]},{"value":"floatingPanelWillBeginDragging:","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillBeginDragging(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floatingPanelWillBeginDragging:"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillBeginDragging(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:shouldAllowToScroll:in:)\/title","op":"replace","value":"floatingPanel:shouldAllowToScroll:in:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:shouldAllowToScroll:in:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"floatingPanel:shouldAllowToScroll:in:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidRemove(_:)\/title","value":"floatingPanelDidRemove:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floatingPanelDidRemove:"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidRemove(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidEndAttracting(_:)\/title","op":"replace","value":"floatingPanelDidEndAttracting:"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelDidEndAttracting(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floatingPanelDidEndAttracting:"}]}]}]}