{"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel"]]},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelpangesturerecognizer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelpangesturerecognizer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIPanGestureRecognizer"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject","doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP","doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/SQ","doc:\/\/com.scenee.FloatingPanel\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/delegate","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/delegateOrigin","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/delegateProxy"]},{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/touchesBegan(_:with:)"],"title":"Instance Methods"}],"metadata":{"modules":[{"name":"FloatingPanel"}],"roleHeading":"Class","title":"FloatingPanelPanGestureRecognizer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FloatingPanelPanGestureRecognizer"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelPanGestureRecognizer"}],"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelPanGestureRecognizer"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelPanGestureRecognizer"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A gesture recognizer that looks for panning (dragging) gestures in a panel."}],"references":{"doc://com.scenee.FloatingPanel/objc(cs)UIPanGestureRecognizer":{"type":"unresolvable","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIPanGestureRecognizer","title":"UIPanGestureRecognizer"},"doc://com.scenee.FloatingPanel/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.scenee.FloatingPanel/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPanGestureRecognizer/delegate":{"type":"topic","title":"delegate","abstract":[{"type":"text","text":"The delegate of the gesture recognizer."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"UIGestureRecognizerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIGestureRecognizerDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/floatingpanel\/floatingpanelpangesturerecognizer\/delegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/delegate"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPanGestureRecognizer/delegateOrigin":{"type":"topic","title":"delegateOrigin","abstract":[{"type":"text","text":"The default object implementing a set methods of the delegate of the gesture recognizer."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegateOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIGestureRecognizerDelegate","text":"UIGestureRecognizerDelegate"}],"url":"\/documentation\/floatingpanel\/floatingpanelpangesturerecognizer\/delegateorigin","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/delegateOrigin"},"doc://com.scenee.FloatingPanel/SQ":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPanGestureRecognizer/delegateProxy":{"type":"topic","title":"delegateProxy","abstract":[{"type":"text","text":"A proxy object to intercept the default behavior of the gesture recognizer."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegateProxy","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizerDelegate","preciseIdentifier":"c:objc(pl)UIGestureRecognizerDelegate"},{"text":"?","kind":"text"}],"url":"\/documentation\/floatingpanel\/floatingpanelpangesturerecognizer\/delegateproxy","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/delegateProxy"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPanGestureRecognizer":{"type":"topic","title":"FloatingPanelPanGestureRecognizer","abstract":[{"type":"text","text":"A gesture recognizer that looks for panning (dragging) gestures in a panel."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FloatingPanelPanGestureRecognizer","kind":"identifier"}],"url":"\/documentation\/floatingpanel\/floatingpanelpangesturerecognizer","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelPanGestureRecognizer"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer"},"doc://com.scenee.FloatingPanel/s7CVarArgP":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.scenee.FloatingPanel/SH":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.scenee.FloatingPanel/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPanGestureRecognizer/touchesBegan(_:with:)":{"type":"topic","title":"touchesBegan(_:with:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"touchesBegan"},{"kind":"text","text":"("},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"text":">, ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier","text":"UIEvent"},{"kind":"text","text":")"}],"url":"\/documentation\/floatingpanel\/floatingpanelpangesturerecognizer\/touchesbegan(_:with:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"touchesBegan:withEvent:","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/touchesBegan(_:with:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPanGestureRecognizer/init":{"type":"topic","title":"init","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"url":"\/documentation\/floatingpanel\/floatingpanelpangesturerecognizer\/init","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/init"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"FloatingPanelPanGestureRecognizer"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"FloatingPanelPanGestureRecognizer","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"FloatingPanelPanGestureRecognizer"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/delegate"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/init","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPanGestureRecognizer\/touchesBegan(_:with:)"]}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIPanGestureRecognizer"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FloatingPanelPanGestureRecognizer"},{"text":" : ","kind":"text"},{"text":"UIPanGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPanGestureRecognizer~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPanGestureRecognizer~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"FloatingPanelPanGestureRecognizer","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPanGestureRecognizer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPanGestureRecognizer\/fragments","value":[{"text":"FloatingPanelPanGestureRecognizer","kind":"identifier"}]},{"value":"touchesBegan:withEvent:","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPanGestureRecognizer~1touchesBegan(_:with:)\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPanGestureRecognizer~1touchesBegan(_:with:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesBegan:withEvent:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}