{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide"},"metadata":{"externalID":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}],"modules":[{"name":"FloatingPanel"}],"symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}],"role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide"},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel"]]},"kind":"symbol","seeAlsoSections":[{"title":"Positions","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/SQ","doc:\/\/com.scenee.FloatingPanel\/SH","doc:\/\/com.scenee.FloatingPanel\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"A representation to specify a bounding box which limit the content size of a panel."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/none","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/safeArea","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/superview"]},{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/Equatable-Implementations","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article"},"doc://com.scenee.FloatingPanel/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SQ","title":"Swift.Equatable"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"kind":"article","url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/equatable-implementations"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide/init(rawValue:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/init(rawValue:)","title":"init(rawValue:)","type":"topic"},"doc://com.scenee.FloatingPanel/SY":{"type":"unresolvable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SY","title":"Swift.RawRepresentable"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide","abstract":[{"text":"A representation to specify a bounding box which limit the content size of a panel.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","title":"FloatingPanelLayoutContentBoundingGuide","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide/superview":{"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/superview","role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide.superview","abstract":[],"kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/superview","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"superview","kind":"identifier"}],"navigatorTitle":[{"text":"FloatingPanelLayoutContentBoundingGuideSuperview","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPosition":{"abstract":[{"text":"Constants describing the position of a panel in a screen","type":"text"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","url":"\/documentation\/floatingpanel\/floatingpanelposition","role":"symbol","title":"FloatingPanelPosition","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FloatingPanelPosition","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"FloatingPanelPosition","kind":"identifier"}],"kind":"symbol"},"doc://com.scenee.FloatingPanel/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SH"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide/none":{"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/none","role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide.none","abstract":[],"kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideNone"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide/safeArea":{"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/safeArea","role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide.safeArea","abstract":[],"kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/safearea","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"safeArea","kind":"identifier"}],"navigatorTitle":[{"text":"FloatingPanelLayoutContentBoundingGuideSafeArea","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","title":"FloatingPanelLayoutReferenceGuide","url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide","role":"symbol","abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelReferenceEdge":{"url":"\/documentation\/floatingpanel\/floatingpanelreferenceedge","kind":"symbol","title":"FloatingPanelReferenceEdge","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelReferenceEdge","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","role":"symbol","abstract":[{"type":"text","text":"Constants that specify the edge of the container of a panel."}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelReferenceEdge"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelLayoutContentBoundingGuide"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/none","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/safeArea","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/superview"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide"],"title":"Positions","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"FloatingPanelLayoutContentBoundingGuide","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/fragments","value":[{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1superview\/title","value":"FloatingPanelLayoutContentBoundingGuideSuperview","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1superview\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideSuperview"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition\/title","value":"FloatingPanelPosition"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition\/fragments","value":[{"kind":"identifier","text":"FloatingPanelPosition"}],"op":"replace"},{"op":"replace","value":"FloatingPanelLayoutContentBoundingGuideNone","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1none\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideNone"}]},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1safeArea\/title","op":"replace","value":"FloatingPanelLayoutContentBoundingGuideSafeArea"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1safeArea\/fragments","value":[{"text":"FloatingPanelLayoutContentBoundingGuideSafeArea","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title","value":"FloatingPanelLayoutReferenceGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments","value":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}]},{"value":"FloatingPanelReferenceEdge","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/fragments","value":[{"text":"FloatingPanelReferenceEdge","kind":"identifier"}],"op":"replace"}]}]}