{"seeAlsoSections":[{"title":"Layouts and Anchors","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}],"title":"FloatingPanelLayoutAnchor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelLayoutAnchor","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}]},"abstract":[{"type":"text","text":"An object that defines how to settles a panel with insets from an edge of a reference rectangle."}],"sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring","doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject","doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP","doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/SQ","doc:\/\/com.scenee.FloatingPanel\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(absoluteInset:edge:referenceGuide:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(fractionalInset:edge:referenceGuide:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/referenceGuide"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/FloatingPanelLayoutAnchoring-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutanchor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutanchor"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.scenee.FloatingPanel/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBottomLayout":{"role":"symbol","title":"FloatingPanelBottomLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBottomLayout"}],"abstract":[{"type":"text","text":"A layout object that lays out a panel in bottom sheet style."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelBottomLayout"}],"url":"\/documentation\/floatingpanel\/floatingpanelbottomlayout"},"doc://com.scenee.FloatingPanel/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SH"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor/init(fractionalInset:edge:referenceGuide:)":{"role":"symbol","title":"init(fractionalInset:edge:referenceGuide:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fractionalInset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"edge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelReferenceEdge","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a layout anchor with the specified inset by a fractional value, edge and reference guide for a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(fractionalInset:edge:referenceGuide:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFractionalInset:edge:referenceGuide:"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor\/init(fractionalinset:edge:referenceguide:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor":{"role":"symbol","title":"FloatingPanelIntrinsicLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with the intrinsic size for a content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor"},"doc://com.scenee.FloatingPanel/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SQ"},"doc://com.scenee.FloatingPanel/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(cs)NSObject"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayout":{"role":"symbol","title":"FloatingPanelLayout","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayout"}],"abstract":[{"type":"text","text":"An interface for generating layout information for a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayout"}],"url":"\/documentation\/floatingpanel\/floatingpanellayout"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor/referenceEdge":{"role":"symbol","title":"referenceEdge","fragments":[{"kind":"identifier","text":"referenceEdge"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/referenceEdge","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor\/referenceedge"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor/referenceGuide":{"role":"symbol","title":"referenceGuide","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"}],"abstract":[{"type":"text","text":"The reference rectangle area for the inset."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/referenceGuide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referenceGuide"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor\/referenceguide"},"doc://com.scenee.FloatingPanel/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor":{"role":"symbol","title":"FloatingPanelLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with insets from an edge of a reference rectangle."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor":{"role":"symbol","title":"FloatingPanelAdaptiveLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with a layout guide of a content view."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor/FloatingPanelLayoutAnchoring-Implementations":{"role":"collectionGroup","title":"FloatingPanelLayoutAnchoring Implementations","abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/FloatingPanelLayoutAnchoring-Implementations","kind":"article","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor\/floatingpanellayoutanchoring-implementations"},"doc://com.scenee.FloatingPanel/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP"},"doc://com.scenee.FloatingPanel/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchoring":{"role":"symbol","title":"FloatingPanelLayoutAnchoring","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}],"abstract":[{"type":"text","text":"An interface for implementing custom layout anchor objects."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchoring"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor/init(absoluteInset:edge:referenceGuide:)":{"role":"symbol","title":"init(absoluteInset:edge:referenceGuide:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"absoluteInset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"edge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelReferenceEdge","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a layout anchor with the specified inset by an absolute value, edge and reference guide for a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(absoluteInset:edge:referenceGuide:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAbsoluteInset:edge:referenceGuide:"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor\/init(absoluteinset:edge:referenceguide:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelLayoutAnchor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/referenceEdge","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/referenceGuide"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(absoluteInset:edge:referenceGuide:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(fractionalInset:edge:referenceGuide:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/FloatingPanelLayoutAnchoring-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Layouts and Anchors","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/title","value":"FloatingPanelBottomLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/fragments","value":[{"kind":"identifier","text":"FloatingPanelBottomLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1init(fractionalInset:edge:referenceGuide:)\/title","value":"initWithFractionalInset:edge:referenceGuide:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1init(fractionalInset:edge:referenceGuide:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFractionalInset:edge:referenceGuide:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/title","value":"FloatingPanelIntrinsicLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/title","value":"FloatingPanelLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1referenceGuide\/title","value":"referenceGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1referenceGuide\/fragments","value":[{"kind":"identifier","text":"referenceGuide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/title","value":"FloatingPanelLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/title","value":"FloatingPanelAdaptiveLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring\/title","value":"FloatingPanelLayoutAnchoring"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1init(absoluteInset:edge:referenceGuide:)\/title","value":"initWithAbsoluteInset:edge:referenceGuide:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1init(absoluteInset:edge:referenceGuide:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbsoluteInset:edge:referenceGuide:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}