{"seeAlsoSections":[{"title":"Layouts and Anchors","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}],"title":"FloatingPanelLayoutAnchoring","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayoutAnchoring","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}]},"abstract":[{"type":"text","text":"An interface for implementing custom layout anchor objects."}],"sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring\/referenceGuide"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring\/layoutConstraints(_:for:)"]}],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutanchoring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutanchoring"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchoring/referenceGuide":{"navigatorTitle":[{"kind":"identifier","text":"referenceGuide"}],"role":"symbol","title":"referenceGuide","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring\/referenceGuide","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayoutanchoring\/referenceguide"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor":{"role":"symbol","title":"FloatingPanelLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with insets from an edge of a reference rectangle."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchoring/layoutConstraints(_:for:)":{"navigatorTitle":[{"kind":"identifier","text":"layoutConstraints:for:"}],"role":"symbol","title":"layoutConstraints(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutConstraints"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring\/layoutConstraints(_:for:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayoutanchoring\/layoutconstraints(_:for:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBottomLayout":{"role":"symbol","title":"FloatingPanelBottomLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBottomLayout"}],"abstract":[{"type":"text","text":"A layout object that lays out a panel in bottom sheet style."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelBottomLayout"}],"url":"\/documentation\/floatingpanel\/floatingpanelbottomlayout"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor":{"role":"symbol","title":"FloatingPanelAdaptiveLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with a layout guide of a content view."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayout":{"role":"symbol","title":"FloatingPanelLayout","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayout"}],"abstract":[{"type":"text","text":"An interface for generating layout information for a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayout"}],"url":"\/documentation\/floatingpanel\/floatingpanellayout"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor":{"role":"symbol","title":"FloatingPanelIntrinsicLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with the intrinsic size for a content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchoring":{"role":"symbol","title":"FloatingPanelLayoutAnchoring","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}],"abstract":[{"type":"text","text":"An interface for implementing custom layout anchor objects."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchoring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelLayoutAnchoring"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring\/referenceGuide"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring\/layoutConstraints(_:for:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Layouts and Anchors","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring~1referenceGuide\/title","value":"referenceGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring~1referenceGuide\/fragments","value":[{"kind":"identifier","text":"referenceGuide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/title","value":"FloatingPanelLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring~1layoutConstraints(_:for:)\/title","value":"layoutConstraints:for:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring~1layoutConstraints(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutConstraints:for:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/title","value":"FloatingPanelBottomLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/fragments","value":[{"kind":"identifier","text":"FloatingPanelBottomLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/title","value":"FloatingPanelAdaptiveLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/title","value":"FloatingPanelLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/title","value":"FloatingPanelIntrinsicLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring\/title","value":"FloatingPanelLayoutAnchoring"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}