{"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelController(py)behavior","title":"behavior","symbolKind":"property","role":"symbol","modules":[{"name":"FloatingPanel"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelBehavior","text":"FloatingPanelBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"behavior"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behavior"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior","text":"FloatingPanelBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelBehavior"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/behavior"},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"]]},"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/behavior"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/behavior"]}],"sections":[],"abstract":[{"text":"The behavior object that the controller manages","type":"text"}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/behavior":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/behavior","navigatorTitle":[{"text":"behavior","kind":"identifier"}],"title":"behavior","abstract":[{"type":"text","text":"The behavior object that the controller manages"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/behavior","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"behavior"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelBehavior","text":"FloatingPanelBehavior"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","navigatorTitle":[{"text":"FloatingPanelController","kind":"identifier"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior","navigatorTitle":[{"text":"FloatingPanelBehavior","kind":"identifier"}],"title":"FloatingPanelBehavior","abstract":[{"text":"An interface for generating behavior information to fine-tune the behavior of a panel.","type":"text"}],"url":"\/documentation\/floatingpanel\/floatingpanelbehavior","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBehavior"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"behavior","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"behavior"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@FloatingPanel@objc(pl)FloatingPanelBehavior","text":"id<FloatingPanelBehavior>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"behavior","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"behavior","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1behavior\/title"},{"value":[{"kind":"identifier","text":"behavior"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1behavior\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"kind":"identifier","text":"FloatingPanelController"}]},{"op":"replace","value":"FloatingPanelBehavior","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/fragments","value":[{"kind":"identifier","text":"FloatingPanelBehavior"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}