{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/childforstatusbarstyle"]},{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/childforstatusbarstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelController(py)childViewControllerForStatusBarStyle","title":"childForStatusBarStyle","navigatorTitle":[{"text":"childViewControllerForStatusBarStyle","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"FloatingPanel"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childForStatusBarStyle"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"childForStatusBarStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForStatusBarStyle"},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/childForStatusBarStyle":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForStatusBarStyle","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/childforstatusbarstyle","title":"childForStatusBarStyle","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"childForStatusBarStyle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"childViewControllerForStatusBarStyle"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" * "},{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}]}]}},{"op":"replace","value":"FloatingPanelController","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title"},{"op":"replace","value":[{"text":"FloatingPanelController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments"},{"value":"childViewControllerForStatusBarStyle","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForStatusBarStyle\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForStatusBarStyle\/fragments","value":[{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}]}]}]}