{"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentInsetAdjustmentBehavior-c.property","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-c.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-c.property"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13FloatingPanel0aB10ControllerC30ContentInsetAdjustmentBehaviorO","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentInsetAdjustmentBehavior-swift.enum","kind":"typeIdentifier","text":"ContentInsetAdjustmentBehavior"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"This property specifies how the content area of the tracking scroll view is modified using "},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/adjustedContentInsets","isActive":true,"type":"reference"},{"type":"text","text":". The default value of this property is FloatingPanelController.ContentInsetAdjustmentBehavior.always."}],"type":"paragraph"}]}],"metadata":{"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelController(py)contentInsetAdjustmentBehavior","modules":[{"name":"FloatingPanel"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"contentInsetAdjustmentBehavior","kind":"identifier"},{"kind":"text","text":": "},{"text":"ContentInsetAdjustmentBehavior","kind":"typeIdentifier","preciseIdentifier":"s:13FloatingPanel0aB10ControllerC30ContentInsetAdjustmentBehaviorO"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"contentInsetAdjustmentBehavior","navigatorTitle":[{"kind":"identifier","text":"contentInsetAdjustmentBehavior"}]},"abstract":[{"type":"text","text":"The behavior for determining the adjusted content offsets."}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/ContentInsetAdjustmentBehavior":{"type":"topic","abstract":[{"text":"Constants indicating how safe area insets are added to the adjusted content inset.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/ContentInsetAdjustmentBehavior","url":"\/documentation\/floatingpanel\/contentinsetadjustmentbehavior","fragments":[{"text":"ContentInsetAdjustmentBehavior","kind":"identifier"}],"title":"ContentInsetAdjustmentBehavior","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/contentInsetAdjustmentBehavior-c.property":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentInsetAdjustmentBehavior-c.property","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"contentInsetAdjustmentBehavior"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-c.property","title":"contentInsetAdjustmentBehavior","type":"topic","abstract":[{"text":"The behavior for determining the adjusted content offsets.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContentInsetAdjustmentBehavior","preciseIdentifier":"s:13FloatingPanel0aB10ControllerC30ContentInsetAdjustmentBehaviorO"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/adjustedContentInsets":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/adjustedContentInsets","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"adjustedContentInsets"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/adjustedcontentinsets","title":"adjustedContentInsets","type":"topic","abstract":[{"type":"text","text":"The content insets of the tracking scroll view derived from this safe area"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adjustedContentInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/ContentInsetAdjustmentBehavior-swift.enum":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentInsetAdjustmentBehavior-swift.enum","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContentInsetAdjustmentBehavior"}],"title":"FloatingPanelController.ContentInsetAdjustmentBehavior","abstract":[{"text":"Constants indicating how safe area insets are added to the adjusted content inset.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentInsetAdjustmentBehavior"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-swift.enum","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"contentInsetAdjustmentBehavior"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"contentInsetAdjustmentBehavior"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/ContentInsetAdjustmentBehavior","kind":"typeIdentifier","text":"ContentInsetAdjustmentBehavior","preciseIdentifier":"c:@M@FloatingPanel@E@ContentInsetAdjustmentBehavior"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"kind":"identifier","text":"FloatingPanelController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentInsetAdjustmentBehavior-c.property\/title","value":"contentInsetAdjustmentBehavior"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentInsetAdjustmentBehavior-c.property\/fragments","value":[{"text":"contentInsetAdjustmentBehavior","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"adjustedContentInsets","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1adjustedContentInsets\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1adjustedContentInsets\/fragments","value":[{"text":"adjustedContentInsets","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}