{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentMode-c.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Constants that define how a panel content fills in the surface."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"contentMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentMode-swift.enum","text":"ContentMode","preciseIdentifier":"s:13FloatingPanel0aB10ControllerC11ContentModeO"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/contentmode-c.property"]},{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/contentmode-c.property"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"contentMode","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13FloatingPanel0aB10ControllerC11ContentModeO","text":"ContentMode","kind":"typeIdentifier"}],"modules":[{"name":"FloatingPanel"}],"roleHeading":"Instance Property","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelController(py)contentMode","role":"symbol","title":"contentMode","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"]]},"kind":"symbol","references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/ContentMode":{"role":"symbol","title":"ContentMode","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/ContentMode","type":"topic","fragments":[{"kind":"identifier","text":"ContentMode"}],"kind":"symbol","url":"\/documentation\/floatingpanel\/contentmode","abstract":[{"type":"text","text":"A flag used to determine how the controller object lays out the content view when the surface position changes."}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/contentMode-c.property":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentMode-c.property","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"contentMode"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentmode-c.property","title":"contentMode","type":"topic","abstract":[{"text":"Constants that define how a panel content fills in the surface.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"s:13FloatingPanel0aB10ControllerC11ContentModeO"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/ContentMode-swift.enum":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentMode-swift.enum","abstract":[{"type":"text","text":"A flag used to determine how the controller object lays out the content view when the surface position changes."}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentmode-swift.enum","title":"FloatingPanelController.ContentMode","type":"topic","navigatorTitle":[{"text":"ContentMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentMode"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"contentMode"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"contentMode","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@FloatingPanel@E@ContentMode","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/ContentMode","kind":"typeIdentifier","text":"ContentMode"},{"text":" ","kind":"text"},{"text":"contentMode","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"FloatingPanelController","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title"},{"value":[{"text":"FloatingPanelController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentMode-c.property\/title","op":"replace","value":"contentMode"},{"op":"replace","value":[{"kind":"identifier","text":"contentMode"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentMode-c.property\/fragments"}]}]}