{"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/layout","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"layout","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"layout"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"layout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout","text":"FloatingPanelLayout","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"FloatingPanel"}],"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelController(py)layout"},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"layout","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout","text":"FloatingPanelLayout"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"You need to call ","type":"text"},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/invalidateLayout()","isActive":true,"type":"reference"},{"text":" if you want to apply a new layout object into the panel","type":"text"},{"type":"text","text":" "},{"text":"immediately.","type":"text"}],"type":"paragraph"}]}],"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/layout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/layout"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The layout object that the controller manages"}],"kind":"symbol","references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayout":{"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayout","abstract":[{"type":"text","text":"An interface for generating layout information for a panel."}],"title":"FloatingPanelLayout","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FloatingPanelLayout","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayout"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/invalidateLayout()":{"title":"invalidateLayout()","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/invalidatelayout()","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/invalidateLayout()","abstract":[{"type":"text","text":"Invalidates all layout information of the panel and apply the "},{"type":"reference","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/layout","isActive":true},{"text":" property into it immediately.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"invalidateLayout"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidateLayout","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/layout":{"title":"layout","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/layout","url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/layout","abstract":[{"type":"text","text":"The layout object that the controller manages"}],"navigatorTitle":[{"text":"layout","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layout","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout","text":"FloatingPanelLayout","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"layout","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"layout","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@FloatingPanel@objc(pl)FloatingPanelLayout","kind":"typeIdentifier","text":"id<FloatingPanelLayout>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"layout"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController"},{"value":[{"text":"FloatingPanelController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/title","value":"FloatingPanelLayout"},{"value":[{"kind":"identifier","text":"FloatingPanelLayout"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1invalidateLayout()\/title","op":"replace","value":"invalidateLayout"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateLayout"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1invalidateLayout()\/fragments"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1layout\/title","value":"layout","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1layout\/fragments","value":[{"text":"layout","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}