{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nearbyState"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","text":"FloatingPanelState","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/nearbystate"]}],"abstract":[{"type":"text","text":"The NearbyState determines that finger’s nearby state."}],"metadata":{"role":"symbol","title":"nearbyState","symbolKind":"property","modules":[{"name":"FloatingPanel"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"nearbyState","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"}],"roleHeading":"Instance Property","externalID":"s:13FloatingPanel0aB10ControllerC11nearbyStateAA0abE0Cvp"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/nearbyState"},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelState":{"url":"\/documentation\/floatingpanel\/floatingpanelstate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelState","kind":"identifier"}],"title":"FloatingPanelState","abstract":[{"type":"text","text":"An object that represents the display state of a panel in a screen."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","role":"symbol","type":"topic","navigatorTitle":[{"text":"FloatingPanelState","kind":"identifier"}],"kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/nearbyState":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/nearbyState","kind":"symbol","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/nearbystate","title":"nearbyState","type":"topic","abstract":[{"type":"text","text":"The NearbyState determines that finger’s nearby state."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nearbyState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"FloatingPanelState","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/title"},{"value":[{"kind":"identifier","text":"FloatingPanelState"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/fragments"},{"op":"replace","value":"FloatingPanelController","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"text":"FloatingPanelController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}