{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeArea"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide\/safearea"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide\/safearea"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide\/safeArea","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeArea"}],"title":"FloatingPanelLayoutReferenceGuide.safeArea","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide@FloatingPanelLayoutReferenceGuideSafeArea","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuideSafeArea"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide/safeArea":{"role":"symbol","title":"FloatingPanelLayoutReferenceGuide.safeArea","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeArea"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide\/safeArea","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuideSafeArea"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide\/safearea"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"role":"symbol","title":"FloatingPanelLayoutReferenceGuide","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}],"abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelLayoutReferenceGuideSafeArea"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuideSafeArea"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuideSafeArea"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide~1safeArea\/title","value":"FloatingPanelLayoutReferenceGuideSafeArea"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide~1safeArea\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuideSafeArea"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title","value":"FloatingPanelLayoutReferenceGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}