{"metadata":{"role":"symbol","externalID":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge@FloatingPanelReferenceEdgeBottom","roleHeading":"Case","navigatorTitle":[{"text":"FloatingPanelReferenceEdgeBottom","kind":"identifier"}],"symbolKind":"case","title":"FloatingPanelReferenceEdge.bottom","modules":[{"name":"FloatingPanel"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge\/bottom","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelreferenceedge\/bottom"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanelreferenceedge\/bottom"]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelReferenceEdge":{"url":"\/documentation\/floatingpanel\/floatingpanelreferenceedge","kind":"symbol","title":"FloatingPanelReferenceEdge","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelReferenceEdge","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","role":"symbol","abstract":[{"type":"text","text":"Constants that specify the edge of the container of a panel."}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelReferenceEdge"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelReferenceEdge/bottom":{"abstract":[],"title":"FloatingPanelReferenceEdge.bottom","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelReferenceEdgeBottom"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge\/bottom","url":"\/documentation\/floatingpanel\/floatingpanelreferenceedge\/bottom","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"bottom","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelReferenceEdgeBottom"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"FloatingPanelReferenceEdgeBottom"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"FloatingPanelReferenceEdgeBottom"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"FloatingPanelReferenceEdge","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/fragments","value":[{"text":"FloatingPanelReferenceEdge","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"FloatingPanelReferenceEdgeBottom","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge~1bottom\/title"},{"value":[{"kind":"identifier","text":"FloatingPanelReferenceEdgeBottom"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge~1bottom\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}