{"kind":"symbol","identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge\/top","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge@FloatingPanelReferenceEdgeTop","role":"symbol","modules":[{"name":"FloatingPanel"}],"roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"}],"navigatorTitle":[{"text":"FloatingPanelReferenceEdgeTop","kind":"identifier"}],"title":"FloatingPanelReferenceEdge.top"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"top"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelreferenceedge\/top"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelreferenceedge\/top"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelReferenceEdge/top":{"navigatorTitle":[{"text":"FloatingPanelReferenceEdgeTop","kind":"identifier"}],"url":"\/documentation\/floatingpanel\/floatingpanelreferenceedge\/top","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge\/top","title":"FloatingPanelReferenceEdge.top","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"top","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelReferenceEdge":{"url":"\/documentation\/floatingpanel\/floatingpanelreferenceedge","kind":"symbol","title":"FloatingPanelReferenceEdge","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelReferenceEdge","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","role":"symbol","abstract":[{"type":"text","text":"Constants that specify the edge of the container of a panel."}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelReferenceEdge"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"FloatingPanelReferenceEdgeTop","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"FloatingPanelReferenceEdgeTop","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"FloatingPanelReferenceEdgeTop"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"FloatingPanelReferenceEdgeTop","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge~1top\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge~1top\/fragments","value":[{"text":"FloatingPanelReferenceEdgeTop","kind":"identifier"}]},{"op":"replace","value":"FloatingPanelReferenceEdge","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/title"},{"value":[{"kind":"identifier","text":"FloatingPanelReferenceEdge"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/fragments"}]}]}