{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"grabberAreaFrame"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/surfaceview\/grabberareaframe"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/grabberAreaFrame","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"grabberAreaFrame"}],"title":"grabberAreaFrame","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceView(py)grabberAreaFrame","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"grabberAreaFrame"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView/grabberAreaFrame":{"role":"symbol","title":"grabberAreaFrame","fragments":[{"kind":"identifier","text":"grabberAreaFrame"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/grabberAreaFrame","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/surfaceview\/grabberareaframe"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView":{"role":"symbol","title":"SurfaceView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurfaceView"}],"abstract":[{"type":"text","text":"A view that presents a surface interface in a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SurfaceView"}],"url":"\/documentation\/floatingpanel\/surfaceview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/title","value":"FloatingPanelSurfaceView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/fragments","value":[{"kind":"identifier","text":"FloatingPanelSurfaceView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}