{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentInsetAdjustmentBehavior-swift.enum","preciseIdentifier":"s:13FloatingPanel0aB10ControllerC30ContentInsetAdjustmentBehaviorO","text":"ContentInsetAdjustmentBehavior"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property specifies how the content area of the tracking scroll view is modified using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/adjustedContentInsets"},{"type":"text","text":". The default value of this property is FloatingPanelController.ContentInsetAdjustmentBehavior.always."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentInsetAdjustmentBehavior-swift.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The behavior for determining the adjusted content offsets."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContentInsetAdjustmentBehavior","preciseIdentifier":"s:13FloatingPanel0aB10ControllerC30ContentInsetAdjustmentBehaviorO"}],"title":"contentInsetAdjustmentBehavior","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelController(py)contentInsetAdjustmentBehavior","modules":[{"name":"FloatingPanel"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/contentInsetAdjustmentBehavior-swift.property":{"role":"symbol","title":"contentInsetAdjustmentBehavior","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContentInsetAdjustmentBehavior","preciseIdentifier":"s:13FloatingPanel0aB10ControllerC30ContentInsetAdjustmentBehaviorO"}],"abstract":[{"type":"text","text":"The behavior for determining the adjusted content offsets."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentInsetAdjustmentBehavior-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-swift.property"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"The new interface displays the related contents and utilities in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/ContentInsetAdjustmentBehavior-swift.enum":{"role":"symbol","title":"FloatingPanelController.ContentInsetAdjustmentBehavior","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentInsetAdjustmentBehavior"}],"abstract":[{"type":"text","text":"Constants indicating how safe area insets are added to the adjusted content inset."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentInsetAdjustmentBehavior-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContentInsetAdjustmentBehavior"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-swift.enum"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/ContentInsetAdjustmentBehavior":{"role":"symbol","title":"ContentInsetAdjustmentBehavior","fragments":[{"kind":"identifier","text":"ContentInsetAdjustmentBehavior"}],"abstract":[{"type":"text","text":"Constants indicating how safe area insets are added to the adjusted content inset."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/ContentInsetAdjustmentBehavior","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/contentinsetadjustmentbehavior"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/adjustedContentInsets":{"role":"symbol","title":"adjustedContentInsets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustedContentInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[{"type":"text","text":"The content insets of the tracking scroll view derived from this safe area"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/adjustedContentInsets","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/adjustedcontentinsets"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"role":"symbol","title":"FloatingPanelController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"abstract":[{"type":"text","text":"A container view controller to display a panel to present contents in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/ContentInsetAdjustmentBehavior","preciseIdentifier":"c:@M@FloatingPanel@E@ContentInsetAdjustmentBehavior","text":"ContentInsetAdjustmentBehavior"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}