{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAttracting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/isattracting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller\/isattracting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/isAttracting","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Boolean value indicating whether a panel controller is attracting the surface to a state anchor."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAttracting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isAttracting","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelController(py)isAttracting","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"isAttracting"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"The new interface displays the related contents and utilities in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"role":"symbol","title":"FloatingPanelController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"abstract":[{"type":"text","text":"A container view controller to display a panel to present contents in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/isAttracting":{"role":"symbol","title":"isAttracting","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAttracting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether a panel controller is attracting the surface to a state anchor."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/isAttracting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAttracting"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/isattracting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isAttracting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isAttracting"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"isAttracting"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"kind":"identifier","text":"FloatingPanelController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1isAttracting\/title","value":"isAttracting"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1isAttracting\/fragments","value":[{"kind":"identifier","text":"isAttracting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}