{"abstract":[{"text":"A panel state indicates the half of a panel is shown.","type":"text"}],"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"Half","kind":"identifier"}],"role":"symbol","symbolKind":"property","title":"half","modules":[{"name":"FloatingPanel"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"half","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","kind":"typeIdentifier","text":"FloatingPanelState"}],"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelState(cpy)Half"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(Half) ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"half"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelstate\/half"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanelstate\/half"]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState\/half","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelState":{"url":"\/documentation\/floatingpanel\/floatingpanelstate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelState","kind":"identifier"}],"title":"FloatingPanelState","abstract":[{"type":"text","text":"An object that represents the display state of a panel in a screen."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","role":"symbol","type":"topic","navigatorTitle":[{"text":"FloatingPanelState","kind":"identifier"}],"kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelState/half":{"role":"symbol","type":"topic","title":"half","navigatorTitle":[{"text":"Half","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"half"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState\/half","url":"\/documentation\/floatingpanel\/floatingpanelstate\/half","abstract":[{"text":"A panel state indicates the half of a panel is shown.","type":"text"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","value":"Half","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"Half","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"Half","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"FloatingPanelState","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/fragments","value":[{"kind":"identifier","text":"FloatingPanelState"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState~1half\/title","value":"Half"},{"op":"replace","value":[{"kind":"identifier","text":"Half"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState~1half\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}