{"abstract":[{"type":"text","text":"Returns a layout anchor with the specified inset by an absolute value, edge and reference guide for a panel."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"absoluteInset","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"text":"edge","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge","text":"FloatingPanelReferenceEdge","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge"},{"kind":"text","text":", "},{"text":"referenceGuide","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An absolute offset to attach the panel from the edge."}],"type":"paragraph"}],"name":"absoluteOffset"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Specify the edge of ","type":"text"},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","type":"reference","isActive":true},{"type":"text","text":"’s view. This is the staring point of the offset."}]}],"name":"edge"},{"name":"referenceGuide","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rectangular area to lay out the content. If it’s set to "},{"code":".safeArea","type":"codeVoice"},{"text":", the panel content lays out inside the safe area of its ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","isActive":true},{"type":"text","text":"’s view."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The inset is an amount to inset a panel from an edge of the reference guide.  The edge refers to a panel"},{"type":"text","text":" "},{"type":"text","text":"positioning."}],"type":"paragraph"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithAbsoluteInset:edge:referenceGuide:"}],"role":"symbol","title":"init(absoluteInset:edge:referenceGuide:)","roleHeading":"Initializer","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelLayoutAnchor(im)initWithAbsoluteInset:edge:referenceGuide:","symbolKind":"init","modules":[{"name":"FloatingPanel"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"absoluteInset"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"edge","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FloatingPanelReferenceEdge","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge"},{"text":", ","kind":"text"},{"text":"referenceGuide","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(absoluteInset:edge:referenceGuide:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanellayoutanchor\/init(absoluteinset:edge:referenceguide:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanellayoutanchor\/init(absoluteinset:edge:referenceguide:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor"]]},"sections":[],"kind":"symbol","references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor":{"abstract":[{"type":"text","text":"An object that defines how to settles a panel with insets from an edge of a reference rectangle."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor","title":"FloatingPanelLayoutAnchor","navigatorTitle":[{"text":"FloatingPanelLayoutAnchor","kind":"identifier"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutAnchor","kind":"identifier"}],"kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor/init(absoluteInset:edge:referenceGuide:)":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(absoluteInset:edge:referenceGuide:)","title":"init(absoluteInset:edge:referenceGuide:)","navigatorTitle":[{"kind":"identifier","text":"initWithAbsoluteInset:edge:referenceGuide:"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor\/init(absoluteinset:edge:referenceguide:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"absoluteInset","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"text":"edge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FloatingPanelReferenceEdge","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge"},{"kind":"text","text":", "},{"text":"referenceGuide","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Returns a layout anchor with the specified inset by an absolute value, edge and reference guide for a panel.","type":"text"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelReferenceEdge":{"url":"\/documentation\/floatingpanel\/floatingpanelreferenceedge","kind":"symbol","title":"FloatingPanelReferenceEdge","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelReferenceEdge","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","role":"symbol","abstract":[{"type":"text","text":"Constants that specify the edge of the container of a panel."}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelReferenceEdge"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","title":"FloatingPanelLayoutReferenceGuide","url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide","role":"symbol","abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithAbsoluteInset:edge:referenceGuide:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithAbsoluteInset:edge:referenceGuide:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAbsoluteInset:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"absoluteInset"},{"kind":"text","text":" "},{"text":"edge:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge","text":"FloatingPanelReferenceEdge","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"edge"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":") "},{"kind":"internalParam","text":"referenceGuide"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"kind":"identifier","text":"FloatingPanelController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/title","value":"FloatingPanelLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/fragments","value":[{"text":"FloatingPanelLayoutAnchor","kind":"identifier"}]},{"value":"initWithAbsoluteInset:edge:referenceGuide:","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1init(absoluteInset:edge:referenceGuide:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbsoluteInset:edge:referenceGuide:"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1init(absoluteInset:edge:referenceGuide:)\/fragments"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/title","op":"replace","value":"FloatingPanelReferenceEdge"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/fragments","value":[{"text":"FloatingPanelReferenceEdge","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"FloatingPanelLayoutReferenceGuide","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title"},{"op":"replace","value":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments"}]}]}