{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Returns a layout anchor with the specified inset by a fractional value, edge and reference guide for a panel."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"fractionalInset","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"text":"edge","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge","kind":"typeIdentifier","text":"FloatingPanelReferenceEdge"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"referenceGuide"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"fractionalOffset","content":[{"type":"paragraph","inlineContent":[{"text":"A fractional value of the size of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"},{"type":"text","text":"’s view to attach the panel from the edge."}]}]},{"name":"edge","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specify the edge of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"},{"type":"text","text":"’s view. This is the staring point of the offset."}]}]},{"content":[{"inlineContent":[{"text":"The rectangular area to lay out the content. If it’s set to ","type":"text"},{"code":".safeArea","type":"codeVoice"},{"type":"text","text":", the panel content lays out inside the safe area of its "},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","isActive":true,"type":"reference"},{"type":"text","text":"’s view."}],"type":"paragraph"}],"name":"referenceGuide"}],"kind":"parameters"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The inset is an amount to inset a panel from the edge of the specified reference guide. The value is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a floating-point number in the range 0.0 to 1.0, where 0.0 represents zero distance from the edge and"},{"text":" ","type":"text"},{"text":"1.0 represents a distance to the opposite edge.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutanchor\/init(fractionalinset:edge:referenceguide:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutanchor\/init(fractionalinset:edge:referenceguide:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(fractionalInset:edge:referenceGuide:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelLayoutAnchor(im)initWithFractionalInset:edge:referenceGuide:","modules":[{"name":"FloatingPanel"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithFractionalInset:edge:referenceGuide:"}],"title":"init(fractionalInset:edge:referenceGuide:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"fractionalInset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"edge"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge","text":"FloatingPanelReferenceEdge","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceGuide"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol"},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelReferenceEdge":{"url":"\/documentation\/floatingpanel\/floatingpanelreferenceedge","kind":"symbol","title":"FloatingPanelReferenceEdge","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelReferenceEdge","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","role":"symbol","abstract":[{"type":"text","text":"Constants that specify the edge of the container of a panel."}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelReferenceEdge"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor/init(fractionalInset:edge:referenceGuide:)":{"type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/init(fractionalInset:edge:referenceGuide:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFractionalInset:edge:referenceGuide:"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor\/init(fractionalinset:edge:referenceguide:)","abstract":[{"type":"text","text":"Returns a layout anchor with the specified inset by a fractional value, edge and reference guide for a panel."}],"title":"init(fractionalInset:edge:referenceGuide:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fractionalInset"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"edge"},{"text":": ","kind":"text"},{"text":"FloatingPanelReferenceEdge","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"referenceGuide"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","title":"FloatingPanelLayoutReferenceGuide","url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide","role":"symbol","abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor":{"abstract":[{"type":"text","text":"An object that defines how to settles a panel with insets from an edge of a reference rectangle."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor","title":"FloatingPanelLayoutAnchor","navigatorTitle":[{"text":"FloatingPanelLayoutAnchor","kind":"identifier"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutAnchor","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithFractionalInset:edge:referenceGuide:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFractionalInset:edge:referenceGuide:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFractionalInset:"},{"kind":"text","text":"("},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"fractionalInset","kind":"internalParam"},{"kind":"text","text":" "},{"text":"edge:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge","text":"FloatingPanelReferenceEdge","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"edge"},{"kind":"text","text":" "},{"text":"referenceGuide:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":") "},{"text":"referenceGuide","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/title","value":"FloatingPanelReferenceEdge","op":"replace"},{"value":[{"kind":"identifier","text":"FloatingPanelReferenceEdge"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/fragments"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController","op":"replace"},{"value":[{"kind":"identifier","text":"FloatingPanelController"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1init(fractionalInset:edge:referenceGuide:)\/title","value":"initWithFractionalInset:edge:referenceGuide:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor~1init(fractionalInset:edge:referenceGuide:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFractionalInset:edge:referenceGuide:"}]},{"value":"FloatingPanelLayoutReferenceGuide","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title"},{"value":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/title","value":"FloatingPanelLayoutAnchor"},{"op":"replace","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/fragments"}]}]}