{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(floatingPanel:animatorForDismissingWithVelocity:) "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanel"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"fpc","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","text":"FloatingPanelController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animatorForDismissingWith","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"velocity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGVector","text":"CGVector"},{"kind":"text","text":") -> "},{"text":"UIViewPropertyAnimator","preciseIdentifier":"c:objc(cs)UIViewPropertyAnimator","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is the spring animator with 0.25 secs."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:animatorfordismissingwith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:animatorfordismissingwith:)"]}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate"]]},"sections":[],"abstract":[{"type":"text","text":"Returns a UIViewPropertyAnimator object to remove\/dismiss a panel from a position."}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:animatorForDismissingWith:)","interfaceLanguage":"swift"},"metadata":{"title":"floatingPanel(_:animatorForDismissingWith:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"floatingPanel:animatorForDismissingWithVelocity:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"floatingPanel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animatorForDismissingWith","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGVector","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGVector"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIViewPropertyAnimator","kind":"typeIdentifier","text":"UIViewPropertyAnimator"}],"required":true,"roleHeading":"Instance Method","modules":[{"name":"FloatingPanel"}],"externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelControllerDelegate(im)floatingPanel:animatorForDismissingWithVelocity:"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:animatorForDismissingWith:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:animatorForDismissingWith:)","abstract":[{"text":"Returns a UIViewPropertyAnimator object to remove\/dismiss a panel from a position.","type":"text"}],"navigatorTitle":[{"text":"floatingPanel:animatorForDismissingWithVelocity:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanel"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":", ","kind":"text"},{"text":"animatorForDismissingWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGVector","text":"CGVector","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewPropertyAnimator","text":"UIViewPropertyAnimator"}],"type":"topic","required":true,"title":"floatingPanel(_:animatorForDismissingWith:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:animatorfordismissingwith:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"abstract":[{"text":"A set of methods implemented by the delegate of a panel controller allows the adopting delegate to respond to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"messages from the FloatingPanelController class and thus respond to, and in some affect, operations such as"},{"type":"text","text":" "},{"type":"text","text":"dragging, attracting a panel, layout of a panel and the content, and transition animations."}],"title":"FloatingPanelControllerDelegate","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelControllerDelegate","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"floatingPanel:animatorForDismissingWithVelocity:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"floatingPanel:animatorForDismissingWithVelocity:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"UIViewPropertyAnimator","preciseIdentifier":"c:objc(cs)UIViewPropertyAnimator"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"floatingPanel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController"},{"kind":"text","text":" *) "},{"text":"fpc","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatorForDismissingWithVelocity:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGVector","text":"CGVector"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"velocity"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"floatingPanel:animatorForDismissingWithVelocity:","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:animatorForDismissingWith:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:animatorForDismissingWith:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"floatingPanel:animatorForDismissingWithVelocity:"}],"op":"replace"},{"op":"replace","value":"FloatingPanelControllerDelegate","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/fragments","op":"replace"},{"op":"replace","value":"FloatingPanelController","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title"},{"value":[{"text":"FloatingPanelController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}