{"abstract":[{"type":"text","text":"Called on start of dragging (may require some time and or distance to move)"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillbegindragging(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillbegindragging(_:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanelWillBeginDragging"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"fpc"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"FloatingPanel"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanelWillBeginDragging"},{"kind":"text","text":"("},{"text":"FloatingPanelController","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":")","kind":"text"}],"externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelControllerDelegate(im)floatingPanelWillBeginDragging:","symbolKind":"method","navigatorTitle":[{"text":"floatingPanelWillBeginDragging:","kind":"identifier"}],"required":true,"title":"floatingPanelWillBeginDragging(_:)"},"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillBeginDragging(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"abstract":[{"text":"A set of methods implemented by the delegate of a panel controller allows the adopting delegate to respond to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"messages from the FloatingPanelController class and thus respond to, and in some affect, operations such as"},{"type":"text","text":" "},{"type":"text","text":"dragging, attracting a panel, layout of a panel and the content, and transition animations."}],"title":"FloatingPanelControllerDelegate","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelControllerDelegate","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelWillBeginDragging(_:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillBeginDragging(_:)","abstract":[{"type":"text","text":"Called on start of dragging (may require some time and or distance to move)"}],"navigatorTitle":[{"text":"floatingPanelWillBeginDragging:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanelWillBeginDragging"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":")","kind":"text"}],"type":"topic","required":true,"title":"floatingPanelWillBeginDragging(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillbegindragging(_:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"floatingPanelWillBeginDragging:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"floatingPanelWillBeginDragging:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"floatingPanelWillBeginDragging:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","text":"FloatingPanelController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"fpc","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/title","op":"replace","value":"FloatingPanelControllerDelegate"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/fragments","value":[{"text":"FloatingPanelControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillBeginDragging(_:)\/title","value":"floatingPanelWillBeginDragging:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"floatingPanelWillBeginDragging:"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillBeginDragging(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","op":"replace","value":"FloatingPanelController"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"text":"FloatingPanelController","kind":"identifier"}]}]}]}