{"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelControllerDelegate(im)floatingPanel:layoutForTraitCollection:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"floatingPanel","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"layoutFor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout","text":"FloatingPanelLayout","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"floatingPanel:layoutForTraitCollection:","kind":"identifier"}],"title":"floatingPanel(_:layoutFor:)","roleHeading":"Instance Method","modules":[{"name":"FloatingPanel"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:layoutFor:)-7vm4h","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(floatingPanel:layoutForTraitCollection:) ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"floatingPanel","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"fpc","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layoutFor"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"newCollection"},{"text":": ","kind":"text"},{"text":"UITraitCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout","text":"FloatingPanelLayout","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:layoutfor:)-7vm4h"]},{"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:layoutfor:)-7vm4h"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Returns a FloatingPanelLayout object. If you use the default one, you can use a "},{"code":"FloatingPanelBottomLayout","type":"codeVoice"},{"type":"text","text":" object."}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"abstract":[{"text":"A set of methods implemented by the delegate of a panel controller allows the adopting delegate to respond to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"messages from the FloatingPanelController class and thus respond to, and in some affect, operations such as"},{"type":"text","text":" "},{"type":"text","text":"dragging, attracting a panel, layout of a panel and the content, and transition animations."}],"title":"FloatingPanelControllerDelegate","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelControllerDelegate","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:layoutFor:)-7vm4h":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:layoutFor:)-7vm4h","abstract":[{"type":"text","text":"Returns a FloatingPanelLayout object. If you use the default one, you can use a "},{"type":"codeVoice","code":"FloatingPanelBottomLayout"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"floatingPanel:layoutForTraitCollection:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"floatingPanel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"layoutFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout","kind":"typeIdentifier","text":"FloatingPanelLayout"}],"type":"topic","title":"floatingPanel(_:layoutFor:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:layoutfor:)-7vm4h","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayout":{"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayout","abstract":[{"type":"text","text":"An interface for generating layout information for a panel."}],"title":"FloatingPanelLayout","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FloatingPanelLayout","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayout"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"floatingPanel:layoutForTraitCollection:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floatingPanel:layoutForTraitCollection:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Qo@M@FloatingPanel@objc(pl)FloatingPanelLayout","kind":"typeIdentifier","text":"id<FloatingPanelLayout>"},{"kind":"text","text":" *) "},{"text":"floatingPanel:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fpc","kind":"internalParam"},{"kind":"text","text":" "},{"text":"layoutForTraitCollection:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"newCollection"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/title","value":"FloatingPanelControllerDelegate"},{"op":"replace","value":[{"text":"FloatingPanelControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/fragments"},{"value":"FloatingPanelController","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title"},{"value":[{"text":"FloatingPanelController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments"},{"value":"floatingPanel:layoutForTraitCollection:","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:layoutFor:)-7vm4h\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:layoutFor:)-7vm4h\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floatingPanel:layoutForTraitCollection:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/title","value":"FloatingPanelLayout","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayout"}],"op":"replace"}]}]}