{"abstract":[{"type":"text","text":"Called on start to remove its view controller from the parent view controller."}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate"]]},"sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillRemove(_:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"floatingPanelWillRemove"},{"kind":"text","text":"("},{"text":"FloatingPanelController","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"text":")","kind":"text"}],"required":true,"externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelControllerDelegate(im)floatingPanelWillRemove:","modules":[{"name":"FloatingPanel"}],"symbolKind":"method","navigatorTitle":[{"text":"floatingPanelWillRemove:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","title":"floatingPanelWillRemove(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(floatingPanelWillRemove:) ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"floatingPanelWillRemove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"fpc","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillremove(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillremove(_:)"]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"abstract":[{"text":"A set of methods implemented by the delegate of a panel controller allows the adopting delegate to respond to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"messages from the FloatingPanelController class and thus respond to, and in some affect, operations such as"},{"type":"text","text":" "},{"type":"text","text":"dragging, attracting a panel, layout of a panel and the content, and transition animations."}],"title":"FloatingPanelControllerDelegate","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelControllerDelegate","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanelWillRemove(_:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanelWillRemove(_:)","abstract":[{"text":"Called on start to remove its view controller from the parent view controller.","type":"text"}],"navigatorTitle":[{"text":"floatingPanelWillRemove:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanelWillRemove"},{"text":"(","kind":"text"},{"text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","required":true,"title":"floatingPanelWillRemove(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanelwillremove(_:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"floatingPanelWillRemove:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"floatingPanelWillRemove:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"floatingPanelWillRemove:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":" *) "},{"text":"fpc","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/title","op":"replace","value":"FloatingPanelControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/fragments","value":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}]},{"op":"replace","value":"floatingPanelWillRemove:","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillRemove(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanelWillRemove(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"floatingPanelWillRemove:","kind":"identifier"}]},{"op":"replace","value":"FloatingPanelController","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title"},{"value":[{"text":"FloatingPanelController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}