{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(Full) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelstate\/full"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelstate\/full"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState\/full","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A panel state indicates the entire panel is shown."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"}],"title":"full","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelState(cpy)Full","modules":[{"name":"FloatingPanel"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelState/full":{"role":"symbol","title":"full","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"}],"abstract":[{"type":"text","text":"A panel state indicates the entire panel is shown."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState\/full","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelstate\/full"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"The new interface displays the related contents and utilities in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelState":{"role":"symbol","title":"FloatingPanelState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelState"}],"abstract":[{"type":"text","text":"An object that represents the display state of a panel in a screen."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelState"}],"url":"\/documentation\/floatingpanel\/floatingpanelstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"},{"kind":"text","text":" * "},{"kind":"identifier","text":"Full"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}