{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"removalInteractionVelocityThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"In case "},{"type":"reference","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:shouldRemoveAt:with:)","isActive":true},{"type":"text","text":" is implemented, this value will not be used. The default value of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelDefaultBehavior"},{"text":" is 5.5","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Returns the velocity threshold for the default interactive removal gesture.","type":"text"}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removalInteractionVelocityThreshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"navigatorTitle":[{"text":"removalInteractionVelocityThreshold","kind":"identifier"}],"title":"removalInteractionVelocityThreshold","modules":[{"name":"FloatingPanel"}],"externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelBehavior(py)removalInteractionVelocityThreshold","role":"symbol"},"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior\/removalinteractionvelocitythreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior\/removalinteractionvelocitythreshold"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/removalInteractionVelocityThreshold"},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/removalInteractionVelocityThreshold":{"abstract":[{"type":"text","text":"Returns the velocity threshold for the default interactive removal gesture."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/removalInteractionVelocityThreshold","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removalInteractionVelocityThreshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"navigatorTitle":[{"text":"removalInteractionVelocityThreshold","kind":"identifier"}],"type":"topic","title":"removalInteractionVelocityThreshold","url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/removalinteractionvelocitythreshold","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior","navigatorTitle":[{"text":"FloatingPanelBehavior","kind":"identifier"}],"title":"FloatingPanelBehavior","abstract":[{"text":"An interface for generating behavior information to fine-tune the behavior of a panel.","type":"text"}],"url":"\/documentation\/floatingpanel\/floatingpanelbehavior","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBehavior"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate/floatingPanel(_:shouldRemoveAt:with:)":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate\/floatingPanel(_:shouldRemoveAt:with:)","abstract":[{"text":"Asks the delegate whether a panel should be removed when dragging ended at the specified location","type":"text"}],"navigatorTitle":[{"text":"floatingPanel:shouldRemoveAtLocation:withVelocity:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floatingPanel"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldRemoveAt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGVector","kind":"typeIdentifier","text":"CGVector"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"floatingPanel(_:shouldRemoveAt:with:)","role":"symbol","kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate\/floatingpanel(_:shouldremoveat:with:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelDefaultBehavior":{"role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelDefaultBehavior","abstract":[{"type":"text","text":"The default behavior object for a panel"}],"kind":"symbol","url":"\/documentation\/floatingpanel\/floatingpaneldefaultbehavior","type":"topic","title":"FloatingPanelDefaultBehavior","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelDefaultBehavior"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelDefaultBehavior"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"removalInteractionVelocityThreshold"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"removalInteractionVelocityThreshold","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"removalInteractionVelocityThreshold"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"removalInteractionVelocityThreshold","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior~1removalInteractionVelocityThreshold\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior~1removalInteractionVelocityThreshold\/fragments","value":[{"kind":"identifier","text":"removalInteractionVelocityThreshold"}],"op":"replace"},{"op":"replace","value":"FloatingPanelBehavior","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/fragments","value":[{"text":"FloatingPanelBehavior","kind":"identifier"}],"op":"replace"},{"value":"floatingPanel:shouldRemoveAtLocation:withVelocity:","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:shouldRemoveAt:with:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"floatingPanel:shouldRemoveAtLocation:withVelocity:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate~1floatingPanel(_:shouldRemoveAt:with:)\/fragments"}]}]}