{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior"]]},"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/springResponseTime","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"A floating-point value that determines the approximate time until a panel stops to an anchor after the user lifts their finger.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"springResponseTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelBehavior(py)springResponseTime","role":"symbol","required":true,"modules":[{"name":"FloatingPanel"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"springResponseTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"springResponseTime"}],"title":"springResponseTime"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior\/springresponsetime"]},{"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior\/springresponsetime"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior","navigatorTitle":[{"text":"FloatingPanelBehavior","kind":"identifier"}],"title":"FloatingPanelBehavior","abstract":[{"text":"An interface for generating behavior information to fine-tune the behavior of a panel.","type":"text"}],"url":"\/documentation\/floatingpanel\/floatingpanelbehavior","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBehavior"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/springResponseTime":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"springResponseTime","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"type":"topic","title":"springResponseTime","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/springResponseTime","url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/springresponsetime","kind":"symbol","role":"symbol","abstract":[{"text":"A floating-point value that determines the approximate time until a panel stops to an anchor after the user lifts their finger.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"springResponseTime"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"springResponseTime","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"springResponseTime"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"springResponseTime","kind":"identifier"}]}]}},{"value":"FloatingPanelBehavior","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/fragments","value":[{"text":"FloatingPanelBehavior","kind":"identifier"}]},{"op":"replace","value":"springResponseTime","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior~1springResponseTime\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior~1springResponseTime\/fragments","value":[{"text":"springResponseTime","kind":"identifier"}]}]}]}