{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"springDecelerationRate"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The oscillation magnitude to attract a panel to an anchor can be adjusted this value between 0.979 and 1.0"},{"type":"text","text":" "},{"type":"text","text":"in increments of 0.001. When this value is around 0.979, the attraction uses a critically damped spring system."},{"text":" ","type":"text"},{"type":"text","text":"When this value is between 0.978 and 1.0, it uses a underdamped spring system with a damping ratio computed by"},{"text":" ","type":"text"},{"type":"text","text":"this value. You shouldn’t return less than 0.979 because the system is overdamped. If the pan gesture’s velocity"},{"text":" ","type":"text"},{"type":"text","text":"is less than 300, this value is ignored and a panel applies a critically damped system."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/springDecelerationRate","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior"]]},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"springDecelerationRate","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"kind":"identifier","text":"springDecelerationRate"}],"externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelBehavior(py)springDecelerationRate","title":"springDecelerationRate","modules":[{"name":"FloatingPanel"}],"required":true,"roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"A floating-point value that determines the rate of oscillation magnitude reduction after the user lifts their finger.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior\/springdecelerationrate"]},{"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior\/springdecelerationrate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior","navigatorTitle":[{"text":"FloatingPanelBehavior","kind":"identifier"}],"title":"FloatingPanelBehavior","abstract":[{"text":"An interface for generating behavior information to fine-tune the behavior of a panel.","type":"text"}],"url":"\/documentation\/floatingpanel\/floatingpanelbehavior","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBehavior"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/springDecelerationRate":{"abstract":[{"type":"text","text":"A floating-point value that determines the rate of oscillation magnitude reduction after the user lifts their finger."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/springDecelerationRate","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"springDecelerationRate","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"kind":"identifier","text":"springDecelerationRate"}],"kind":"symbol","title":"springDecelerationRate","required":true,"url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/springdecelerationrate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"springDecelerationRate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"springDecelerationRate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":" ","kind":"text"},{"kind":"identifier","text":"springDecelerationRate"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"FloatingPanelBehavior","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/title"},{"value":[{"text":"FloatingPanelBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/fragments","op":"replace"},{"value":"springDecelerationRate","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior~1springDecelerationRate\/title"},{"value":[{"kind":"identifier","text":"springDecelerationRate"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior~1springDecelerationRate\/fragments"}]}]}