{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","text":"FloatingPanelLayoutReferenceGuide"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/referenceguide"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/referenceguide"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/referenceGuide","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"FloatingPanelLayoutAnchoring.referenceGuide"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"}],"title":"referenceGuide","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelAdaptiveLayoutAnchor(py)referenceGuide","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"referenceGuide"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor/referenceGuide":{"role":"symbol","title":"referenceGuide","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/referenceGuide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referenceGuide"}],"url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/referenceguide"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"role":"symbol","title":"FloatingPanelLayoutReferenceGuide","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}],"abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor":{"role":"symbol","title":"FloatingPanelAdaptiveLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with a layout guide of a content view."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"referenceGuide"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"referenceGuide"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","text":"FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1referenceGuide\/title","value":"referenceGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1referenceGuide\/fragments","value":[{"kind":"identifier","text":"referenceGuide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title","value":"FloatingPanelLayoutReferenceGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/title","value":"FloatingPanelAdaptiveLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}