{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hitTest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/grabberview\/hittest(_:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/grabberview\/hittest(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/hitTest(_:with:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hitTest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"title":"hitTest(_:with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelGrabberView(im)hitTest:withEvent:","modules":[{"name":"FloatingPanel"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/GrabberView/hitTest(_:with:)":{"role":"symbol","title":"hitTest(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hitTest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView\/hitTest(_:with:)","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/grabberview\/hittest(_:with:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/GrabberView":{"role":"symbol","title":"GrabberView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GrabberView"}],"abstract":[{"type":"text","text":"A view that presents a grabber handle in the surface of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/GrabberView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GrabberView"}],"url":"\/documentation\/floatingpanel\/grabberview"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"The new interface displays the related contents and utilities in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"hitTest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"point"},{"kind":"text","text":" "},{"kind":"identifier","text":"withEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}