{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentBoundingGuide","kind":"identifier"},{"kind":"text","text":": "},{"text":"FloatingPanelLayoutContentBoundingGuide","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/contentboundingguide"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/contentboundingguide"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"contentBoundingGuide","kind":"identifier"}],"modules":[{"name":"FloatingPanel"}],"roleHeading":"Instance Property","title":"contentBoundingGuide","role":"symbol","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelAdaptiveLayoutAnchor(py)contentBoundingGuide","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"contentBoundingGuide","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide","text":"FloatingPanelLayoutContentBoundingGuide"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/contentBoundingGuide"},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor/contentBoundingGuide":{"url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/contentboundingguide","type":"topic","abstract":[],"title":"contentBoundingGuide","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/contentBoundingGuide","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"contentBoundingGuide"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentBoundingGuide"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide","text":"FloatingPanelLayoutContentBoundingGuide","kind":"typeIdentifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor":{"type":"topic","url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor","abstract":[{"text":"An object that defines how to settles a panel with a layout guide of a content view.","type":"text"}],"title":"FloatingPanelAdaptiveLayoutAnchor","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FloatingPanelAdaptiveLayoutAnchor","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide","abstract":[{"text":"A representation to specify a bounding box which limit the content size of a panel.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","title":"FloatingPanelLayoutContentBoundingGuide","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutContentBoundingGuide","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"contentBoundingGuide","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"contentBoundingGuide"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FloatingPanelLayoutContentBoundingGuide","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide"},{"text":" ","kind":"text"},{"text":"contentBoundingGuide","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1contentBoundingGuide\/title","op":"replace","value":"contentBoundingGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1contentBoundingGuide\/fragments","value":[{"text":"contentBoundingGuide","kind":"identifier"}]},{"value":"FloatingPanelAdaptiveLayoutAnchor","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}]},{"value":"FloatingPanelLayoutContentBoundingGuide","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}]}]}]}