{"metadata":{"role":"collectionGroup","title":"FloatingPanelLayoutAnchoring Implementations","modules":[{"name":"FloatingPanel"}]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/layoutConstraints(_:for:)"],"generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor"]]},"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/FloatingPanelLayoutAnchoring-Implementations","interfaceLanguage":"swift"},"kind":"article","variants":[{"paths":["\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/floatingpanellayoutanchoring-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/floatingpanellayoutanchoring-implementations"]}],"sections":[],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor/layoutConstraints(_:for:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutConstraints","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition","text":"FloatingPanelPosition","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"layoutConstraints:for:","kind":"identifier"}],"abstract":[],"title":"layoutConstraints(_:for:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/layoutConstraints(_:for:)","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/layoutconstraints(_:for:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor":{"type":"topic","url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor","abstract":[{"text":"An object that defines how to settles a panel with a layout guide of a content view.","type":"text"}],"title":"FloatingPanelAdaptiveLayoutAnchor","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FloatingPanelAdaptiveLayoutAnchor","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/layoutConstraints(_:for:)"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1layoutConstraints(_:for:)\/title","value":"layoutConstraints:for:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"layoutConstraints:for:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1layoutConstraints(_:for:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/title","op":"replace","value":"FloatingPanelAdaptiveLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}