{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"superview"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/superview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/superview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/superview","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"superview"}],"title":"FloatingPanelLayoutContentBoundingGuide.superview","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide@FloatingPanelLayoutContentBoundingGuideSuperview","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideSuperview"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide":{"role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}],"abstract":[{"type":"text","text":"A representation to specify a bounding box which limit the content size of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide/superview":{"role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide.superview","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"superview"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide\/superview","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideSuperview"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide\/superview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelLayoutContentBoundingGuideSuperview"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideSuperview"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideSuperview"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/title","value":"FloatingPanelLayoutContentBoundingGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1superview\/title","value":"FloatingPanelLayoutContentBoundingGuideSuperview"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide~1superview\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuideSuperview"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}