{"abstract":[{"type":"text","text":"Returns a layout anchor with the specified offset by a fractional value and reference guide for a panel."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/init(fractionaloffset:referenceguide:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/init(fractionaloffset:referenceguide:)"]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithFractionalOffset:referenceGuide:","kind":"identifier"}],"role":"symbol","title":"init(fractionalOffset:referenceGuide:)","symbolKind":"init","modules":[{"name":"FloatingPanel"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fractionalOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"referenceGuide"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelIntrinsicLayoutAnchor(im)initWithFractionalOffset:referenceGuide:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fractionalOffset"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"offset"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"referenceGuide","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":" = .safeArea)"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"fractionalOffset","content":[{"inlineContent":[{"type":"text","text":"A fractional offset of the content size in the main dimension(i.e. y axis for a bottom panel) to attach the panel."}],"type":"paragraph"}]},{"name":"referenceGuide","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rectangular area to lay out the content. If it’s set to "},{"type":"codeVoice","code":".safeArea"},{"type":"text","text":", the panel content lays out inside the safe area of its "},{"type":"reference","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","isActive":true},{"text":"’s view.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"The offset value is a floating-point number in the range 0.0 to 1.0, where 0.0 represents the full content"},{"text":" ","type":"text"},{"text":"is displayed and 0.5 represents the half of content is displayed.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/init(fractionalOffset:referenceGuide:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor":{"navigatorTitle":[{"text":"FloatingPanelIntrinsicLayoutAnchor","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelIntrinsicLayoutAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor","kind":"symbol","title":"FloatingPanelIntrinsicLayoutAnchor","url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor","role":"symbol","abstract":[{"text":"An object that defines how to settles a panel with the intrinsic size for a content.","type":"text"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","title":"FloatingPanelLayoutReferenceGuide","url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide","role":"symbol","abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor/init(fractionalOffset:referenceGuide:)":{"abstract":[{"type":"text","text":"Returns a layout anchor with the specified offset by a fractional value and reference guide for a panel."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fractionalOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"referenceGuide","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/init(fractionaloffset:referenceguide:)","title":"init(fractionalOffset:referenceGuide:)","type":"topic","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/init(fractionalOffset:referenceGuide:)","navigatorTitle":[{"kind":"identifier","text":"initWithFractionalOffset:referenceGuide:"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFractionalOffset:referenceGuide:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFractionalOffset:referenceGuide:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFractionalOffset:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"offset"},{"kind":"text","text":" "},{"text":"referenceGuide:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"referenceGuide"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/title","value":"FloatingPanelIntrinsicLayoutAnchor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/fragments","value":[{"text":"FloatingPanelIntrinsicLayoutAnchor","kind":"identifier"}]},{"value":"FloatingPanelLayoutReferenceGuide","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}]},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor~1init(fractionalOffset:referenceGuide:)\/title","value":"initWithFractionalOffset:referenceGuide:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor~1init(fractionalOffset:referenceGuide:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFractionalOffset:referenceGuide:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","op":"replace","value":[{"text":"FloatingPanelController","kind":"identifier"}]}]}]}