{"metadata":{"title":"init(absoluteOffset:referenceGuide:)","role":"symbol","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"absoluteOffset"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"referenceGuide","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"text":")","kind":"text"}],"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelIntrinsicLayoutAnchor(im)initWithAbsoluteOffset:referenceGuide:","navigatorTitle":[{"text":"initWithAbsoluteOffset:referenceGuide:","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"FloatingPanel"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/init(absoluteOffset:referenceGuide:)"},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor"]]},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/init(absoluteoffset:referenceguide:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/init(absoluteoffset:referenceguide:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Returns a layout anchor with the specified offset by an absolute value and reference guide for a panel.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"absoluteOffset"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"offset"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"referenceGuide"},{"text":": ","kind":"text"},{"text":"FloatingPanelLayoutReferenceGuide","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"text":" = .safeArea)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An absolute offset from the content size in the main dimension(i.e. y axis for a bottom panel) to attach the panel."}],"type":"paragraph"}],"name":"absoluteOffset"},{"name":"referenceGuide","content":[{"type":"paragraph","inlineContent":[{"text":"The rectangular area to lay out the content. If it’s set to ","type":"text"},{"code":".safeArea","type":"codeVoice"},{"type":"text","text":", the panel content lays out inside the safe area of its "},{"type":"reference","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","isActive":true},{"text":"’s view.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The offset is an amount to offset a position of panel that displays the entire content from an edge of"},{"text":" ","type":"text"},{"type":"text","text":"the reference guide.  The edge refers to a panel positioning."}]}],"kind":"content"}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor":{"navigatorTitle":[{"text":"FloatingPanelIntrinsicLayoutAnchor","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelIntrinsicLayoutAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor","kind":"symbol","title":"FloatingPanelIntrinsicLayoutAnchor","url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor","role":"symbol","abstract":[{"text":"An object that defines how to settles a panel with the intrinsic size for a content.","type":"text"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","abstract":[{"text":"A container view controller to display a panel to present contents in parallel as a user wants.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","title":"FloatingPanelLayoutReferenceGuide","url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide","role":"symbol","abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor/init(absoluteOffset:referenceGuide:)":{"title":"init(absoluteOffset:referenceGuide:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"absoluteOffset"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"referenceGuide","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/init(absoluteoffset:referenceguide:)","navigatorTitle":[{"text":"initWithAbsoluteOffset:referenceGuide:","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/init(absoluteOffset:referenceGuide:)","abstract":[{"type":"text","text":"Returns a layout anchor with the specified offset by an absolute value and reference guide for a panel."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithAbsoluteOffset:referenceGuide:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAbsoluteOffset:referenceGuide:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAbsoluteOffset:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"text":") ","kind":"text"},{"text":"offset","kind":"internalParam"},{"kind":"text","text":" "},{"text":"referenceGuide:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"referenceGuide","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/title","op":"replace","value":"FloatingPanelIntrinsicLayoutAnchor"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/fragments","op":"replace","value":[{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController"},{"op":"replace","value":[{"text":"FloatingPanelController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title","op":"replace","value":"FloatingPanelLayoutReferenceGuide"},{"value":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments"},{"op":"replace","value":"initWithAbsoluteOffset:referenceGuide:","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor~1init(absoluteOffset:referenceGuide:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor~1init(absoluteOffset:referenceGuide:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAbsoluteOffset:referenceGuide:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}