{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/referenceguide"]},{"paths":["\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/referenceguide"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"The reference rectangle area for the offset","type":"text"}],"sections":[],"metadata":{"title":"referenceGuide","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelIntrinsicLayoutAnchor(py)referenceGuide","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"referenceGuide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier"}],"modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"text":"referenceGuide","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/referenceGuide"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"referenceGuide","kind":"identifier"},{"kind":"text","text":": "},{"text":"FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","title":"FloatingPanelLayoutReferenceGuide","url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide","role":"symbol","abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor":{"navigatorTitle":[{"text":"FloatingPanelIntrinsicLayoutAnchor","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelIntrinsicLayoutAnchor","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor","kind":"symbol","title":"FloatingPanelIntrinsicLayoutAnchor","url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor","role":"symbol","abstract":[{"text":"An object that defines how to settles a panel with the intrinsic size for a content.","type":"text"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor/referenceGuide":{"navigatorTitle":[{"kind":"identifier","text":"referenceGuide"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"referenceGuide","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/referenceGuide","kind":"symbol","title":"referenceGuide","url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/referenceguide","role":"symbol","abstract":[{"text":"The reference rectangle area for the offset","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"referenceGuide"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"referenceGuide","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"FloatingPanelLayoutReferenceGuide","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title"},{"value":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/title","op":"replace","value":"FloatingPanelIntrinsicLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}]},{"value":"referenceGuide","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor~1referenceGuide\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelIntrinsicLayoutAnchor~1referenceGuide\/fragments","value":[{"text":"referenceGuide","kind":"identifier"}],"op":"replace"}]}]}