{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelSurfaceView\/position"},"metadata":{"role":"symbol","title":"position","fragments":[{"text":"position","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"FloatingPanel"}],"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceView(py)position","navigatorTitle":[{"kind":"identifier","text":"position"}],"roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelsurfaceview\/position"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition","kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"}],"languages":["occ"]}]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelSurfaceView/position":{"url":"\/documentation\/floatingpanel\/floatingpanelsurfaceview\/position","title":"position","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"position","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelSurfaceView\/position"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SurfaceView"}],"title":"SurfaceView","abstract":[{"type":"text","text":"A view that presents a surface interface in a panel."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SurfaceView","kind":"identifier"}],"type":"topic","url":"\/documentation\/floatingpanel\/surfaceview","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPosition":{"abstract":[{"text":"Constants describing the position of a panel in a screen","type":"text"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","url":"\/documentation\/floatingpanel\/floatingpanelposition","role":"symbol","title":"FloatingPanelPosition","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FloatingPanelPosition","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"FloatingPanelPosition","kind":"identifier"}],"kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/title","value":"FloatingPanelSurfaceView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/fragments","value":[{"text":"FloatingPanelSurfaceView","kind":"identifier"}]},{"value":"FloatingPanelPosition","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition\/fragments","op":"replace","value":[{"text":"FloatingPanelPosition","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}