{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"absoluteOffset"},{"kind":"text","text":" "},{"kind":"internalParam","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILayoutGuide","preciseIdentifier":"c:objc(cs)UILayoutGuide"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","text":"FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentBoundingGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide","text":"FloatingPanelLayoutContentBoundingGuide"},{"kind":"text","text":" = .none)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"absoluteOffset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An absolute offset from the content size in the main dimension(i.e. y axis for a bottom panel) to attach the panel."}]}]},{"name":"contentLayout","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The content layout guide to calculate the content size in the panel."}]}]},{"name":"referenceGuide","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rectangular area to lay out the content of a panel. If it’s set to "},{"type":"codeVoice","code":".safeArea"},{"type":"text","text":", the panel content displays inside the safe area of its "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController"},{"type":"text","text":"‘s view. This argument doesn’t limit its content size."}]}]},{"name":"contentBoundingGuide","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rectangular area to restrict the content size of a panel in the main dimension(i.e. y axis is the main dimension for a bottom panel)."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The offset is an amount to offset a position of panel that displays the entire content of the specified guide from an edge of"},{"type":"text","text":" "},{"type":"text","text":"the reference guide.  The edge refers to a panel positioning."}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/contentBoundingGuide"},{"type":"text","text":" restricts the content size which a panel displays. For example, given "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/referenceGuide"},{"type":"text","text":" is "},{"type":"codeVoice","code":".superview"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/contentBoundingGuide"},{"type":"text","text":" is "},{"type":"codeVoice","code":".safeArea"},{"type":"text","text":" for a bottom positioned panel, the panel content is laid out inside the superview of the view of FloatingPanelController(not its safe area), but its content size is limited to its safe area size. Normally both of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/referenceGuide"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/contentBoundingGuide"},{"type":"text","text":" are specified with the same rectangle area."}]},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/contentBoundingGuide"},{"type":"text","text":" is set to none, the panel may expand out of the screen size, depending on the intrinsic size of its content."}]}],"type":"aside","name":"Warning"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/init(absoluteoffset:contentlayout:referenceguide:contentboundingguide:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/init(absoluteoffset:contentlayout:referenceguide:contentboundingguide:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/init(absoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a layout anchor with the specified offset by an absolute value to display a panel with its intrinsic content size."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"absoluteOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILayoutGuide","preciseIdentifier":"c:objc(cs)UILayoutGuide"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentBoundingGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutContentBoundingGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide"},{"kind":"text","text":")"}],"title":"init(absoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelAdaptiveLayoutAnchor(im)initWithAbsoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAbsoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor":{"role":"symbol","title":"FloatingPanelAdaptiveLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with a layout guide of a content view."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor/init(absoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:)":{"role":"symbol","title":"init(absoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"absoluteOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILayoutGuide","preciseIdentifier":"c:objc(cs)UILayoutGuide"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contentBoundingGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutContentBoundingGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a layout anchor with the specified offset by an absolute value to display a panel with its intrinsic content size."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/init(absoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAbsoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:"}],"url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/init(absoluteoffset:contentlayout:referenceguide:contentboundingguide:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"role":"symbol","title":"FloatingPanelLayoutReferenceGuide","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}],"abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor/contentBoundingGuide":{"role":"symbol","title":"contentBoundingGuide","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentBoundingGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutContentBoundingGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/contentBoundingGuide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentBoundingGuide"}],"url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/contentboundingguide"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutContentBoundingGuide":{"role":"symbol","title":"FloatingPanelLayoutContentBoundingGuide","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}],"abstract":[{"type":"text","text":"A representation to specify a bounding box which limit the content size of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutcontentboundingguide"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelAdaptiveLayoutAnchor/referenceGuide":{"role":"symbol","title":"referenceGuide","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelAdaptiveLayoutAnchor\/referenceGuide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"referenceGuide"}],"url":"\/documentation\/floatingpanel\/floatingpaneladaptivelayoutanchor\/referenceguide"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"role":"symbol","title":"FloatingPanelController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"abstract":[{"type":"text","text":"A container view controller to display a panel to present contents in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAbsoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbsoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAbsoluteOffset:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"offset"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentLayout:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UILayoutGuide","preciseIdentifier":"c:objc(cs)UILayoutGuide"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contentLayout"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceGuide:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide","text":"FloatingPanelLayoutReferenceGuide"},{"kind":"text","text":") "},{"kind":"internalParam","text":"referenceGuide"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentBoundingGuide:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutContentBoundingGuide","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelLayoutContentBoundingGuide","text":"FloatingPanelLayoutContentBoundingGuide"},{"kind":"text","text":") "},{"kind":"internalParam","text":"contentBoundingGuide"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/title","value":"FloatingPanelAdaptiveLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelAdaptiveLayoutAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1init(absoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:)\/title","value":"initWithAbsoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1init(absoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbsoluteOffset:contentLayout:referenceGuide:contentBoundingGuide:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title","value":"FloatingPanelLayoutReferenceGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1contentBoundingGuide\/title","value":"contentBoundingGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1contentBoundingGuide\/fragments","value":[{"kind":"identifier","text":"contentBoundingGuide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/title","value":"FloatingPanelLayoutContentBoundingGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutContentBoundingGuide\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutContentBoundingGuide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1referenceGuide\/title","value":"referenceGuide"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelAdaptiveLayoutAnchor~1referenceGuide\/fragments","value":[{"kind":"identifier","text":"referenceGuide"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"kind":"identifier","text":"FloatingPanelController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}