{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"superview"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide"]]},"kind":"symbol","metadata":{"externalID":"c:@M@FloatingPanel@E@FloatingPanelLayoutReferenceGuide@FloatingPanelLayoutReferenceGuideSuperview","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"superview","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"FloatingPanel"}],"symbolKind":"case","title":"FloatingPanelLayoutReferenceGuide.superview","role":"symbol","navigatorTitle":[{"text":"FloatingPanelLayoutReferenceGuideSuperview","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide\/superview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide\/superview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide\/superview","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide/superview":{"kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide\/superview","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuideSuperview"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"superview","kind":"identifier"}],"abstract":[],"title":"FloatingPanelLayoutReferenceGuide.superview","url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide\/superview","type":"topic"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutReferenceGuide":{"navigatorTitle":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutReferenceGuide","kind":"symbol","title":"FloatingPanelLayoutReferenceGuide","url":"\/documentation\/floatingpanel\/floatingpanellayoutreferenceguide","role":"symbol","abstract":[{"type":"text","text":"A representation to specify a rectangular area to lay out a panel."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"FloatingPanelLayoutReferenceGuideSuperview","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"FloatingPanelLayoutReferenceGuideSuperview","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"FloatingPanelLayoutReferenceGuideSuperview"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide~1superview\/title","value":"FloatingPanelLayoutReferenceGuideSuperview"},{"value":[{"text":"FloatingPanelLayoutReferenceGuideSuperview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide~1superview\/fragments"},{"value":"FloatingPanelLayoutReferenceGuide","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutReferenceGuide\/fragments","value":[{"text":"FloatingPanelLayoutReferenceGuide","kind":"identifier"}]}]}]}