{"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView"]]},"abstract":[{"type":"text","text":"The content view to be assigned a view of the content view controller of "},{"code":"FloatingPanelController","type":"codeVoice"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/surfaceview\/contentview"]},{"paths":["\/documentation\/floatingpanel\/surfaceview\/contentview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"?","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/contentView","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"contentView","kind":"identifier"}],"role":"symbol","modules":[{"name":"FloatingPanel"}],"title":"contentView","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceView(py)contentView","symbolKind":"property"},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView/contentView":{"title":"contentView","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/contentView","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The content view to be assigned a view of the content view controller of "},{"code":"FloatingPanelController","type":"codeVoice"}],"navigatorTitle":[{"text":"contentView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentView"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"url":"\/documentation\/floatingpanel\/surfaceview\/contentview","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SurfaceView"}],"title":"SurfaceView","abstract":[{"type":"text","text":"A view that presents a surface interface in a panel."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SurfaceView","kind":"identifier"}],"type":"topic","url":"\/documentation\/floatingpanel\/surfaceview","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"contentView","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"contentView","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" * ","kind":"text"},{"text":"contentView","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"contentView","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView~1contentView\/title"},{"value":[{"kind":"identifier","text":"contentView"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView~1contentView\/fragments"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/title","value":"FloatingPanelSurfaceView","op":"replace"},{"value":[{"kind":"identifier","text":"FloatingPanelSurfaceView"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}