{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/surfaceview\/containermargins"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/surfaceview\/containermargins"]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/containerMargins"},"metadata":{"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceView(py)containerMargins","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containerMargins","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"FloatingPanel"}],"symbolKind":"property","title":"containerMargins","role":"symbol","navigatorTitle":[{"text":"containerMargins","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containerMargins"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"The margins to use when laying out the container view wrapping content.","type":"text"}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SurfaceView"}],"title":"SurfaceView","abstract":[{"type":"text","text":"A view that presents a surface interface in a panel."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SurfaceView","kind":"identifier"}],"type":"topic","url":"\/documentation\/floatingpanel\/surfaceview","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView/containerMargins":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/containerMargins","abstract":[{"text":"The margins to use when laying out the container view wrapping content.","type":"text"}],"url":"\/documentation\/floatingpanel\/surfaceview\/containermargins","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containerMargins","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"}],"title":"containerMargins","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"containerMargins"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"containerMargins"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"containerMargins","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containerMargins"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/title","value":"FloatingPanelSurfaceView"},{"op":"replace","value":[{"kind":"identifier","text":"FloatingPanelSurfaceView"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView~1containerMargins\/title","value":"containerMargins"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView~1containerMargins\/fragments","value":[{"kind":"identifier","text":"containerMargins"}],"op":"replace"}]}]}