{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/grabberAreaOffset"},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceView(py)grabberAreaOffset","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"FloatingPanel"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"grabberAreaOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"text":"grabberAreaOffset","kind":"identifier"}],"title":"grabberAreaOffset"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/surfaceview\/grabberareaoffset"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/surfaceview\/grabberareaoffset"]}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView"]]},"abstract":[{"type":"text","text":"The offset from the move edge to prevent the content scroll"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"grabberAreaOffset"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView/grabberAreaOffset":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/grabberAreaOffset","abstract":[{"type":"text","text":"The offset from the move edge to prevent the content scroll"}],"url":"\/documentation\/floatingpanel\/surfaceview\/grabberareaoffset","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"grabberAreaOffset","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"text":"grabberAreaOffset","kind":"identifier"}],"kind":"symbol","title":"grabberAreaOffset"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView":{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SurfaceView"}],"title":"SurfaceView","abstract":[{"type":"text","text":"A view that presents a surface interface in a panel."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SurfaceView","kind":"identifier"}],"type":"topic","url":"\/documentation\/floatingpanel\/surfaceview","role":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"grabberAreaOffset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"grabberAreaOffset","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"text":" ","kind":"text"},{"text":"grabberAreaOffset","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView~1grabberAreaOffset\/title","value":"grabberAreaOffset","op":"replace"},{"value":[{"text":"grabberAreaOffset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView~1grabberAreaOffset\/fragments","op":"replace"},{"op":"replace","value":"FloatingPanelSurfaceView","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceView\/fragments","op":"replace","value":[{"text":"FloatingPanelSurfaceView","kind":"identifier"}]}]}]}