{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceAppearance","text":"SurfaceAppearance"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/surfaceview\/appearance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/surfaceview\/appearance"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/appearance","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The appearance settings for a surface view."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SurfaceAppearance","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceAppearance"}],"title":"appearance","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceView(py)appearance","modules":[{"name":"FloatingPanel"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView/appearance":{"role":"symbol","title":"appearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SurfaceAppearance","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceAppearance"}],"abstract":[{"type":"text","text":"The appearance settings for a surface view."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView\/appearance","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/surfaceview\/appearance"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"The new interface displays the related contents and utilities in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceView":{"role":"symbol","title":"SurfaceView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurfaceView"}],"abstract":[{"type":"text","text":"A view that presents a surface interface in a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SurfaceView"}],"url":"\/documentation\/floatingpanel\/surfaceview"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceAppearance":{"role":"symbol","title":"SurfaceAppearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurfaceAppearance"}],"abstract":[{"type":"text","text":"An object for customizing the appearance of a surface view"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SurfaceAppearance"}],"url":"\/documentation\/floatingpanel\/surfaceappearance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceAppearance","text":"FloatingPanelSurfaceAppearance"},{"kind":"text","text":" * "},{"kind":"identifier","text":"appearance"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}