{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout\/anchors","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anchors"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayoutAnchoring","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring","text":"FloatingPanelLayoutAnchoring"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/floatingpanel\/floatingpanelbottomlayout\/anchors"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/floatingpanelbottomlayout\/anchors"]}],"metadata":{"roleHeading":"Instance Property","title":"anchors","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelBottomLayout(py)anchors","navigatorTitle":[{"kind":"identifier","text":"anchors"}],"modules":[{"name":"FloatingPanel"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"anchors","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayoutAnchoring","text":"FloatingPanelLayoutAnchoring"},{"text":"]","kind":"text"}]},"abstract":[{"type":"text","text":"Returns the layout anchors to specify the snapping locations for each state."}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelState":{"url":"\/documentation\/floatingpanel\/floatingpanelstate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelState","kind":"identifier"}],"title":"FloatingPanelState","abstract":[{"type":"text","text":"An object that represents the display state of a panel in a screen."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","role":"symbol","type":"topic","navigatorTitle":[{"text":"FloatingPanelState","kind":"identifier"}],"kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBottomLayout":{"abstract":[{"text":"A layout object that lays out a panel in bottom sheet style.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelBottomLayout","kind":"identifier"}],"title":"FloatingPanelBottomLayout","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelbottomlayout","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelBottomLayout"}],"type":"topic"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchoring":{"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchoring","type":"topic","abstract":[{"text":"An interface for implementing custom layout anchor objects.","type":"text"}],"title":"FloatingPanelLayoutAnchoring","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchoring","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutAnchoring"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FloatingPanelLayoutAnchoring","kind":"identifier"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBottomLayout/anchors":{"title":"anchors","navigatorTitle":[{"kind":"identifier","text":"anchors"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout\/anchors","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelbottomlayout\/anchors","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"anchors","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"text":" : ","kind":"text"},{"text":"FloatingPanelLayoutAnchoring","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayoutAnchoring","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns the layout anchors to specify the snapping locations for each state."}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"anchors","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"anchors"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<FloatingPanelState *,id<FloatingPanelLayoutAnchoring>>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"anchors","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"FloatingPanelState","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/title"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/fragments","op":"replace","value":[{"text":"FloatingPanelState","kind":"identifier"}]},{"value":"FloatingPanelBottomLayout","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/title"},{"op":"replace","value":[{"text":"FloatingPanelBottomLayout","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/fragments"},{"value":"FloatingPanelLayoutAnchoring","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring\/title"},{"value":[{"text":"FloatingPanelLayoutAnchoring","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchoring\/fragments","op":"replace"},{"value":"anchors","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout~1anchors\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout~1anchors\/fragments","value":[{"text":"anchors","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}