{"metadata":{"title":"initialState","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"text":"initialState","kind":"identifier"}],"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelBottomLayout(py)initialState","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialState"},{"text":": ","kind":"text"},{"text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialState","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","text":"FloatingPanelState"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Returns the initial state when a panel is presented."}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout\/initialState","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelbottomlayout\/initialstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelbottomlayout\/initialstate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBottomLayout":{"abstract":[{"text":"A layout object that lays out a panel in bottom sheet style.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelBottomLayout","kind":"identifier"}],"title":"FloatingPanelBottomLayout","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout","role":"symbol","url":"\/documentation\/floatingpanel\/floatingpanelbottomlayout","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelBottomLayout"}],"type":"topic"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBottomLayout/initialState":{"type":"topic","title":"initialState","url":"\/documentation\/floatingpanel\/floatingpanelbottomlayout\/initialstate","abstract":[{"type":"text","text":"Returns the initial state when a panel is presented."}],"navigatorTitle":[{"kind":"identifier","text":"initialState"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialState"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout\/initialState"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelState":{"url":"\/documentation\/floatingpanel\/floatingpanelstate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingPanelState","kind":"identifier"}],"title":"FloatingPanelState","abstract":[{"type":"text","text":"An object that represents the display state of a panel in a screen."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","role":"symbol","type":"topic","navigatorTitle":[{"text":"FloatingPanelState","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initialState"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"initialState"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"},{"text":" * ","kind":"text"},{"text":"initialState","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/title","value":"FloatingPanelBottomLayout"},{"value":[{"kind":"identifier","text":"FloatingPanelBottomLayout"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout~1initialState\/title","op":"replace","value":"initialState"},{"op":"replace","value":[{"text":"initialState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout~1initialState\/fragments"},{"value":"FloatingPanelState","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/fragments","value":[{"kind":"identifier","text":"FloatingPanelState"}]}]}]}