{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelposition\/bottom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelposition\/bottom"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition\/bottom","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"}],"title":"FloatingPanelPosition.bottom","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@FloatingPanel@E@FloatingPanelPosition@FloatingPanelPositionBottom","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelPositionBottom"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPosition/bottom":{"role":"symbol","title":"FloatingPanelPosition.bottom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition\/bottom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelPositionBottom"}],"url":"\/documentation\/floatingpanel\/floatingpanelposition\/bottom"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPosition":{"role":"symbol","title":"FloatingPanelPosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelPosition"}],"abstract":[{"type":"text","text":"Constants describing the position of a panel in a screen"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelPosition"}],"url":"\/documentation\/floatingpanel\/floatingpanelposition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelPositionBottom"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FloatingPanelPositionBottom"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FloatingPanelPositionBottom"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition~1bottom\/title","value":"FloatingPanelPositionBottom"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition~1bottom\/fragments","value":[{"kind":"identifier","text":"FloatingPanelPositionBottom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition\/title","value":"FloatingPanelPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition\/fragments","value":[{"kind":"identifier","text":"FloatingPanelPosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}