{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutConstraints"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition","text":"FloatingPanelPosition"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/layoutconstraints(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/layoutconstraints(_:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/layoutConstraints(_:for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"FloatingPanelLayoutAnchoring.layoutConstraints(_:for:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"layoutConstraints(_:for:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutConstraints"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"]"}],"symbolKind":"method","externalID":"c:@CM@FloatingPanel@objc(cs)FloatingPanelIntrinsicLayoutAnchor(im)layoutConstraints:for:","extendedModule":"FloatingPanel","modules":[{"name":"FloatingPanel"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/FloatingPanelLayoutAnchoring-Implementations"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"The new interface displays the related contents and utilities in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPosition":{"role":"symbol","title":"FloatingPanelPosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelPosition"}],"abstract":[{"type":"text","text":"Constants describing the position of a panel in a screen"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelPosition"}],"url":"\/documentation\/floatingpanel\/floatingpanelposition"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor/FloatingPanelLayoutAnchoring-Implementations":{"role":"collectionGroup","title":"FloatingPanelLayoutAnchoring Implementations","abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/FloatingPanelLayoutAnchoring-Implementations","kind":"article","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/floatingpanellayoutanchoring-implementations"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor/layoutConstraints(_:for:)":{"role":"symbol","title":"layoutConstraints(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutConstraints"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor\/layoutConstraints(_:for:)","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor\/layoutconstraints(_:for:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelIntrinsicLayoutAnchor":{"role":"symbol","title":"FloatingPanelIntrinsicLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with the intrinsic size for a content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelIntrinsicLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelIntrinsicLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpanelintrinsiclayoutanchor"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"role":"symbol","title":"FloatingPanelController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"abstract":[{"type":"text","text":"A container view controller to display a panel to present contents in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<NSLayoutConstraint *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"layoutConstraints:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"vc"},{"kind":"text","text":" "},{"kind":"identifier","text":"for:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition","text":"FloatingPanelPosition"},{"kind":"text","text":") "},{"kind":"internalParam","text":"position"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}}],"traits":[{"interfaceLanguage":"occ"}]}]}