{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectionalProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fpc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The progress is represented by a floating-point value between 0.0 and 1.0, inclusive, where 1.0 indicates a panel is impossible to move to the next position. The default value is 0.5. Values less than 0.0 and greater than 1.0 are pinned to those limits."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior\/redirectionalprogress(_:from:to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelbehavior\/redirectionalprogress(_:from:to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/redirectionalProgress(_:from:to:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the progress to redirect to the previous position."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectionalProgress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"redirectionalProgress(_:from:to:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelBehavior(im)redirectionalProgress:from:to:","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"redirectionalProgress:from:to:"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior/redirectionalProgress(_:from:to:)":{"role":"symbol","title":"redirectionalProgress(_:from:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectionalProgress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"Returns the progress to redirect to the previous position."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior\/redirectionalProgress(_:from:to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"redirectionalProgress:from:to:"}],"url":"\/documentation\/floatingpanel\/floatingpanelbehavior\/redirectionalprogress(_:from:to:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBehavior":{"role":"symbol","title":"FloatingPanelBehavior","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBehavior"}],"abstract":[{"type":"text","text":"An interface for generating behavior information to fine-tune the behavior of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBehavior","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelBehavior"}],"url":"\/documentation\/floatingpanel\/floatingpanelbehavior"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelState":{"role":"symbol","title":"FloatingPanelState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelState"}],"abstract":[{"type":"text","text":"An object that represents the display state of a panel in a screen."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelState"}],"url":"\/documentation\/floatingpanel\/floatingpanelstate"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"role":"symbol","title":"FloatingPanelController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"abstract":[{"type":"text","text":"A container view controller to display a panel to present contents in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"redirectionalProgress:from:to:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"redirectionalProgress:from:to:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"identifier","text":"redirectionalProgress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","text":"FloatingPanelController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fpc"},{"kind":"text","text":" "},{"kind":"identifier","text":"from:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"from"},{"kind":"text","text":" "},{"kind":"identifier","text":"to:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState","text":"FloatingPanelState"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"to"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior~1redirectionalProgress(_:from:to:)\/title","value":"redirectionalProgress:from:to:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior~1redirectionalProgress(_:from:to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"redirectionalProgress:from:to:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/title","value":"FloatingPanelBehavior"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBehavior\/fragments","value":[{"kind":"identifier","text":"FloatingPanelBehavior"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/title","value":"FloatingPanelState"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelState\/fragments","value":[{"kind":"identifier","text":"FloatingPanelState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"kind":"identifier","text":"FloatingPanelController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}