{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareLayout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"surfaceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelbottomlayout\/preparelayout(surfaceview:in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelbottomlayout\/preparelayout(surfaceview:in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout\/prepareLayout(surfaceView:in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns layout constraints to determine the cross dimension of a panel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareLayout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"surfaceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"]"}],"title":"prepareLayout(surfaceView:in:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelBottomLayout(im)prepareLayoutWithSurfaceView:in:","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"prepareLayoutWithSurfaceView:in:"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBottomLayout/prepareLayout(surfaceView:in:)":{"role":"symbol","title":"prepareLayout(surfaceView:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareLayout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"surfaceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns layout constraints to determine the cross dimension of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout\/prepareLayout(surfaceView:in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareLayoutWithSurfaceView:in:"}],"url":"\/documentation\/floatingpanel\/floatingpanelbottomlayout\/preparelayout(surfaceview:in:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelBottomLayout":{"role":"symbol","title":"FloatingPanelBottomLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelBottomLayout"}],"abstract":[{"type":"text","text":"A layout object that lays out a panel in bottom sheet style."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelBottomLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelBottomLayout"}],"url":"\/documentation\/floatingpanel\/floatingpanelbottomlayout"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"prepareLayoutWithSurfaceView:in:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareLayoutWithSurfaceView:in:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<NSLayoutConstraint *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"prepareLayoutWithSurfaceView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"surfaceView"},{"kind":"text","text":" "},{"kind":"identifier","text":"in:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout~1prepareLayout(surfaceView:in:)\/title","value":"prepareLayoutWithSurfaceView:in:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout~1prepareLayout(surfaceView:in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareLayoutWithSurfaceView:in:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/title","value":"FloatingPanelBottomLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelBottomLayout\/fragments","value":[{"kind":"identifier","text":"FloatingPanelBottomLayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}