{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition","text":"FloatingPanelPosition"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanellayout\/position"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanellayout\/position"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout\/position","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the position of a panel in a "},{"type":"codeVoice","code":"FloatingPanelController"},{"type":"text","text":" view ."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"position"}],"role":"symbol","title":"position","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition"}],"symbolKind":"property","externalID":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout(py)position","required":true,"modules":[{"name":"FloatingPanel"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayout":{"role":"symbol","title":"FloatingPanelLayout","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayout"}],"abstract":[{"type":"text","text":"An interface for generating layout information for a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayout"}],"url":"\/documentation\/floatingpanel\/floatingpanellayout"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayout/position":{"navigatorTitle":[{"kind":"identifier","text":"position"}],"role":"symbol","title":"position","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition"}],"abstract":[{"type":"text","text":"Returns the position of a panel in a "},{"type":"codeVoice","code":"FloatingPanelController"},{"type":"text","text":" view ."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayout\/position","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayout\/position"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelPosition":{"role":"symbol","title":"FloatingPanelPosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelPosition"}],"abstract":[{"type":"text","text":"Constants describing the position of a panel in a screen"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelPosition"}],"url":"\/documentation\/floatingpanel\/floatingpanelposition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"position"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"position"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelPosition","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelPosition","text":"FloatingPanelPosition"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/title","value":"FloatingPanelLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout~1position\/title","value":"position"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayout~1position\/fragments","value":[{"kind":"identifier","text":"position"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition\/title","value":"FloatingPanelPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelPosition\/fragments","value":[{"kind":"identifier","text":"FloatingPanelPosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}