{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","preciseIdentifier":"c:@M@FloatingPanel@E@FloatingPanelReferenceEdge","text":"FloatingPanelReferenceEdge"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceEdge"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanellayoutanchor\/referenceedge"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/referenceEdge","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"referenceEdge"}],"title":"referenceEdge","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelLayoutAnchor(py)referenceEdge","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"referenceEdge"}]},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor":{"role":"symbol","title":"FloatingPanelLayoutAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}],"abstract":[{"type":"text","text":"An object that defines how to settles a panel with insets from an edge of a reference rectangle."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}],"url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelLayoutAnchor/referenceEdge":{"role":"symbol","title":"referenceEdge","fragments":[{"kind":"identifier","text":"referenceEdge"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelLayoutAnchor\/referenceEdge","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanellayoutanchor\/referenceedge"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelReferenceEdge":{"role":"symbol","title":"FloatingPanelReferenceEdge","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelReferenceEdge"}],"abstract":[{"type":"text","text":"Constants that specify the edge of the container of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelReferenceEdge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelReferenceEdge"}],"url":"\/documentation\/floatingpanel\/floatingpanelreferenceedge"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/title","value":"FloatingPanelLayoutAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelLayoutAnchor\/fragments","value":[{"kind":"identifier","text":"FloatingPanelLayoutAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/title","value":"FloatingPanelReferenceEdge"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelReferenceEdge\/fragments","value":[{"kind":"identifier","text":"FloatingPanelReferenceEdge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}