{"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"title":"FloatingPanelController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelController","modules":[{"name":"FloatingPanel"}],"navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}]},"abstract":[{"type":"text","text":"A container view controller to display a panel to present contents in parallel as a user wants."}],"sections":[],"identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSCoding","doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject","doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP","doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP","doc:\/\/com.scenee.FloatingPanel\/SQ","doc:\/\/com.scenee.FloatingPanel\/SH","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearanceContainer","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIContentContainer","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusEnvironment","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIStateRestoring","doc:\/\/com.scenee.FloatingPanel\/5UIKit23UITraitChangeObservableP","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UITraitEnvironment","doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/init(coder:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/init(delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/adjustedContentInsets","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/backdropView","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/behavior","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForHomeIndicatorAutoHidden","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForScreenEdgesDeferringSystemGestures","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForStatusBarHidden","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForStatusBarStyle","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentInsetAdjustmentBehavior-swift.property","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentMode-swift.property","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentViewController","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/delegate","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/isAttracting","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/isRemovalInteractionEnabled","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/layout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/nearbyState","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/panGestureRecognizer","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/state","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/surfaceLocation","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/surfaceView","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/trackingScrollView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/accessibilityPerformEscape()","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/addPanel(toParent:at:animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/followScrollViewBouncing()","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/hide(animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/invalidateLayout()","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/loadView()","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/move(to:animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/removePanelFromParent(animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/set(contentViewController:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/show(animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/surfaceLocation(for:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/track(scrollView:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/untrack(scrollView:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/viewDidLayoutSubviews()","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/viewWillDisappear(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/viewWillTransition(to:with:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/willTransition(to:with:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentInsetAdjustmentBehavior-swift.enum","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentMode-swift.enum"]}],"variants":[{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/floatingpanel\/floatingpanelcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/init(coder:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/ContentInsetAdjustmentBehavior-swift.enum":{"role":"symbol","title":"FloatingPanelController.ContentInsetAdjustmentBehavior","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentInsetAdjustmentBehavior"}],"abstract":[{"type":"text","text":"Constants indicating how safe area insets are added to the adjusted content inset."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentInsetAdjustmentBehavior-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContentInsetAdjustmentBehavior"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-swift.enum"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/childForStatusBarHidden":{"role":"symbol","title":"childForStatusBarHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childForStatusBarHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForStatusBarHidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/childforstatusbarhidden"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/invalidateLayout()":{"role":"symbol","title":"invalidateLayout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateLayout"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Invalidates all layout information of the panel and apply the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/layout"},{"type":"text","text":" property into it immediately."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/invalidateLayout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidateLayout"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/invalidatelayout()"},"doc://com.scenee.FloatingPanel/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSCoding"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelControllerDelegate","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelControllerDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initialize a newly created panel controller."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/init(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/init(delegate:)"},"doc://com.scenee.FloatingPanel/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SQ"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelControllerDelegate":{"role":"symbol","title":"FloatingPanelControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"abstract":[{"type":"text","text":"A set of methods implemented by the delegate of a panel controller allows the adopting delegate to respond to"},{"type":"text","text":" "},{"type":"text","text":"messages from the FloatingPanelController class and thus respond to, and in some affect, operations such as"},{"type":"text","text":" "},{"type":"text","text":"dragging, attracting a panel, layout of a panel and the content, and transition animations."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontrollerdelegate"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/move(to:animated:completion:)":{"role":"symbol","title":"move(to:animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"move"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Moves the position to the specified position."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/move(to:animated:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"moveToState:animated:completion:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/move(to:animated:completion:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/surfaceLocation":{"role":"symbol","title":"surfaceLocation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"surfaceLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"type":"text","text":"The surface’s position in a panel controller’s view."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/surfaceLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"surfaceLocation"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/surfacelocation"},"doc://com.scenee.FloatingPanel/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIUserActivityRestoring"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/loadView()":{"role":"symbol","title":"loadView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadView"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Creates the view that the controller manages."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/loadView()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadView"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/loadview()"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/trackingScrollView":{"role":"symbol","title":"trackingScrollView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingScrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the scroll view that the controller tracks."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/trackingScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingScrollView"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/trackingscrollview"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelControllerDelegate","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelControllerDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate of a panel controller object."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/delegate"},"doc://com.scenee.FloatingPanel/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIFocusEnvironment"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/childForStatusBarStyle":{"role":"symbol","title":"childForStatusBarStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childForStatusBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForStatusBarStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/childforstatusbarstyle"},"doc://com.scenee.FloatingPanel/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/layout":{"role":"symbol","title":"layout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelLayout","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelLayout"}],"abstract":[{"type":"text","text":"The layout object that the controller manages"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/layout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layout"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/layout"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/surfaceLocation(for:)":{"role":"symbol","title":"surfaceLocation(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"surfaceLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"type":"text","text":"Returns the surface’s position in a panel controller’s view for the specified state."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/surfaceLocation(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"surfaceLocationFor:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/surfacelocation(for:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/removePanelFromParent(animated:completion:)":{"role":"symbol","title":"removePanelFromParent(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removePanelFromParent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Removes the controller and the managed view from its parent view controller"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/removePanelFromParent(animated:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removePanelFromParent:completion:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/removepanelfromparent(animated:completion:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/childForHomeIndicatorAutoHidden":{"role":"symbol","title":"childForHomeIndicatorAutoHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childForHomeIndicatorAutoHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForHomeIndicatorAutoHidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForHomeIndicatorAutoHidden"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/childforhomeindicatorautohidden"},"doc://com.scenee.FloatingPanel/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.scenee.FloatingPanel/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIContentContainer"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController":{"role":"symbol","title":"FloatingPanelController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"}],"abstract":[{"type":"text","text":"A container view controller to display a panel to present contents in parallel as a user wants."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FloatingPanelController"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller"},"doc://com.scenee.FloatingPanel/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIViewController"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/contentViewController":{"role":"symbol","title":"contentViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The view controller responsible for the content portion of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentViewController"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentviewcontroller"},"doc://com.scenee.FloatingPanel/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIStateRestoring"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/behavior":{"role":"symbol","title":"behavior","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"behavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelBehavior","preciseIdentifier":"c:@M@FloatingPanel@objc(pl)FloatingPanelBehavior"}],"abstract":[{"type":"text","text":"The behavior object that the controller manages"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/behavior","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"behavior"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/behavior"},"doc://com.scenee.FloatingPanel/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.scenee.FloatingPanel\/SH"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/surfaceView":{"role":"symbol","title":"surfaceView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"surfaceView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SurfaceView","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceView"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Returns the surface view managed by the controller object. It’s the same as "},{"type":"codeVoice","code":"self.view"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/surfaceView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"surfaceView"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/surfaceview"},"doc://com.scenee.FloatingPanel/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.scenee.FloatingPanel\/s23CustomStringConvertibleP"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/untrack(scrollView:)":{"role":"symbol","title":"untrack(scrollView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"untrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Cancel tracking the specify scroll view."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/untrack(scrollView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"untrackScrollView:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/untrack(scrollview:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/set(contentViewController:)":{"role":"symbol","title":"set(contentViewController:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"contentViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Sets the view controller responsible for the content portion of a panel."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/set(contentViewController:)","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/set(contentviewcontroller:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/nearbyState":{"role":"symbol","title":"nearbyState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nearbyState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"}],"abstract":[{"type":"text","text":"The NearbyState determines that finger’s nearby state."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/nearbyState","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/nearbystate"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/show(animated:completion:)":{"role":"symbol","title":"show(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Shows the surface view at the initial position defined by the current layout"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/show(animated:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"show:completion:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/show(animated:completion:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"role":"collection","title":"FloatingPanel","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/followScrollViewBouncing()":{"role":"symbol","title":"followScrollViewBouncing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"followScrollViewBouncing"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"[Experimental] Allows the panel to move as its tracking scroll view bounces."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/followScrollViewBouncing()","kind":"symbol","type":"topic","url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/followscrollviewbouncing()"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/isRemovalInteractionEnabled":{"role":"symbol","title":"isRemovalInteractionEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRemovalInteractionEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value that determines whether the removal interaction is enabled."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/isRemovalInteractionEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRemovalInteractionEnabled"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/isremovalinteractionenabled"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/backdropView":{"role":"symbol","title":"backdropView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backdropView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BackdropView","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelBackdropView"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Returns the backdrop view managed by the controller object."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/backdropView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backdropView"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/backdropview"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/panGestureRecognizer":{"role":"symbol","title":"panGestureRecognizer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"panGestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelPanGestureRecognizer","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelPanGestureRecognizer"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/panGestureRecognizer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"panGestureRecognizer"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/pangesturerecognizer"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/addPanel(toParent:at:animated:completion:)":{"role":"symbol","title":"addPanel(toParent:at:animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPanel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toParent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Adds the view managed by the controller as a child of the specified view controller."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/addPanel(toParent:at:animated:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPanelToParent:at:animated:completion:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/addpanel(toparent:at:animated:completion:)"},"doc://com.scenee.FloatingPanel/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSExtensionRequestHandling"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/viewdidlayoutsubviews()"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/accessibilityPerformEscape()":{"role":"symbol","title":"accessibilityPerformEscape()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityPerformEscape"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/accessibilityPerformEscape()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessibilityPerformEscape"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/accessibilityperformescape()"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/track(scrollView:)":{"role":"symbol","title":"track(scrollView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"track"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tracks the specified scroll view to correspond with the scroll."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/track(scrollView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackScrollView:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/track(scrollview:)"},"doc://com.scenee.FloatingPanel/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UITraitEnvironment"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/hide(animated:completion:)":{"role":"symbol","title":"hide(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Hides the surface view to the hidden position"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/hide(animated:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hide:completion:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/hide(animated:completion:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/isAttracting":{"role":"symbol","title":"isAttracting","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAttracting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether a panel controller is attracting the surface to a state anchor."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/isAttracting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAttracting"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/isattracting"},"doc://com.scenee.FloatingPanel/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIAppearanceContainer"},"doc://com.scenee.FloatingPanel/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)NSObject"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FloatingPanelState","preciseIdentifier":"c:@M@FloatingPanel@objc(cs)FloatingPanelState"}],"abstract":[{"type":"text","text":"The current position of a panel controller’s contents."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/state","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"state"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/state"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/adjustedContentInsets":{"role":"symbol","title":"adjustedContentInsets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustedContentInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[{"type":"text","text":"The content insets of the tracking scroll view derived from this safe area"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/adjustedContentInsets","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustedContentInsets"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/adjustedcontentinsets"},"doc://com.scenee.FloatingPanel/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.scenee.FloatingPanel\/s28CustomDebugStringConvertibleP"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/viewWillDisappear(_:)":{"role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/viewWillDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/viewwilldisappear(_:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/willTransition(to:with:)":{"role":"symbol","title":"willTransition(to:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/willTransition(to:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willTransitionToTraitCollection:withTransitionCoordinator:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/willtransition(to:with:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/initwithnibname:bundle:"},"doc://com.scenee.FloatingPanel/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.scenee.FloatingPanel\/objc(pl)UIResponderStandardEditActions"},"doc://com.scenee.FloatingPanel/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.scenee.FloatingPanel\/s7CVarArgP"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/childForScreenEdgesDeferringSystemGestures":{"role":"symbol","title":"childForScreenEdgesDeferringSystemGestures","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"childForScreenEdgesDeferringSystemGestures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForScreenEdgesDeferringSystemGestures","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"childViewControllerForScreenEdgesDeferringSystemGestures"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/childforscreenedgesdeferringsystemgestures"},"doc://com.scenee.FloatingPanel/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.scenee.FloatingPanel\/5UIKit23UITraitChangeObservableP"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/contentMode-swift.property":{"role":"symbol","title":"contentMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"s:13FloatingPanel0aB10ControllerC11ContentModeO"}],"abstract":[{"type":"text","text":"Constants that define how a panel content fills in the surface."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentMode-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentMode"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentmode-swift.property"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/ContentMode-swift.enum":{"role":"symbol","title":"FloatingPanelController.ContentMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentMode"}],"abstract":[{"type":"text","text":"A flag used to determine how the controller object lays out the content view when the surface position changes."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/ContentMode-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContentMode"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentmode-swift.enum"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/viewWillTransition(to:with:)":{"role":"symbol","title":"viewWillTransition(to:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/viewWillTransition(to:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/viewwilltransition(to:with:)"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/FloatingPanelController/contentInsetAdjustmentBehavior-swift.property":{"role":"symbol","title":"contentInsetAdjustmentBehavior","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentInsetAdjustmentBehavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContentInsetAdjustmentBehavior","preciseIdentifier":"s:13FloatingPanel0aB10ControllerC30ContentInsetAdjustmentBehaviorO"}],"abstract":[{"type":"text","text":"The behavior for determining the adjusted content offsets."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentInsetAdjustmentBehavior-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentInsetAdjustmentBehavior"}],"url":"\/documentation\/floatingpanel\/floatingpanelcontroller\/contentinsetadjustmentbehavior-swift.property"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FloatingPanelController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FloatingPanelController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FloatingPanelController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/adjustedContentInsets","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/backdropView","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/behavior","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForHomeIndicatorAutoHidden","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForScreenEdgesDeferringSystemGestures","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForStatusBarHidden","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/childForStatusBarStyle","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentInsetAdjustmentBehavior-swift.property","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentMode-swift.property","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/contentViewController","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/delegate","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/isAttracting","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/isRemovalInteractionEnabled","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/layout","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/panGestureRecognizer","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/state","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/surfaceLocation","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/surfaceView","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/trackingScrollView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/accessibilityPerformEscape()","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/addPanel(toParent:at:animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/hide(animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/init(coder:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/init(delegate:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/initWithNibName:bundle:","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/invalidateLayout()","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/loadView()","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/move(to:animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/removePanelFromParent(animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/show(animated:completion:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/surfaceLocation(for:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/track(scrollView:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/untrack(scrollView:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/viewDidLayoutSubviews()","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/viewWillDisappear(_:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/viewWillTransition(to:with:)","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelController\/willTransition(to:with:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.scenee.FloatingPanel\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/FloatingPanelControllerDelegate"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FloatingPanelController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForStatusBarHidden\/title","value":"childViewControllerForStatusBarHidden"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForStatusBarHidden\/fragments","value":[{"kind":"identifier","text":"childViewControllerForStatusBarHidden"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1invalidateLayout()\/title","value":"invalidateLayout"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1invalidateLayout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1init(delegate:)\/title","value":"initWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1init(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/title","value":"FloatingPanelControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelControllerDelegate\/fragments","value":[{"kind":"identifier","text":"FloatingPanelControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1move(to:animated:completion:)\/title","value":"moveToState:animated:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1move(to:animated:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToState:animated:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1surfaceLocation\/title","value":"surfaceLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1surfaceLocation\/fragments","value":[{"kind":"identifier","text":"surfaceLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1loadView()\/title","value":"loadView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1loadView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1trackingScrollView\/title","value":"trackingScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1trackingScrollView\/fragments","value":[{"kind":"identifier","text":"trackingScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForStatusBarStyle\/title","value":"childViewControllerForStatusBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForStatusBarStyle\/fragments","value":[{"kind":"identifier","text":"childViewControllerForStatusBarStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1layout\/title","value":"layout"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1layout\/fragments","value":[{"kind":"identifier","text":"layout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1surfaceLocation(for:)\/title","value":"surfaceLocationFor:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1surfaceLocation(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"surfaceLocationFor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1removePanelFromParent(animated:completion:)\/title","value":"removePanelFromParent:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1removePanelFromParent(animated:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removePanelFromParent:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForHomeIndicatorAutoHidden\/title","value":"childViewControllerForHomeIndicatorAutoHidden"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForHomeIndicatorAutoHidden\/fragments","value":[{"kind":"identifier","text":"childViewControllerForHomeIndicatorAutoHidden"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/title","value":"FloatingPanelController"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController\/fragments","value":[{"kind":"identifier","text":"FloatingPanelController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentViewController\/title","value":"contentViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentViewController\/fragments","value":[{"kind":"identifier","text":"contentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1behavior\/title","value":"behavior"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1behavior\/fragments","value":[{"kind":"identifier","text":"behavior"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1surfaceView\/title","value":"surfaceView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1surfaceView\/fragments","value":[{"kind":"identifier","text":"surfaceView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1untrack(scrollView:)\/title","value":"untrackScrollView:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1untrack(scrollView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"untrackScrollView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1show(animated:completion:)\/title","value":"show:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1show(animated:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"show:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1isRemovalInteractionEnabled\/title","value":"isRemovalInteractionEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1isRemovalInteractionEnabled\/fragments","value":[{"kind":"identifier","text":"isRemovalInteractionEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1backdropView\/title","value":"backdropView"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1backdropView\/fragments","value":[{"kind":"identifier","text":"backdropView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1panGestureRecognizer\/title","value":"panGestureRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1panGestureRecognizer\/fragments","value":[{"kind":"identifier","text":"panGestureRecognizer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1addPanel(toParent:at:animated:completion:)\/title","value":"addPanelToParent:at:animated:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1addPanel(toParent:at:animated:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPanelToParent:at:animated:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1accessibilityPerformEscape()\/title","value":"accessibilityPerformEscape"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1accessibilityPerformEscape()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityPerformEscape"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1track(scrollView:)\/title","value":"trackScrollView:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1track(scrollView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackScrollView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1hide(animated:completion:)\/title","value":"hide:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1hide(animated:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hide:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1isAttracting\/title","value":"isAttracting"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1isAttracting\/fragments","value":[{"kind":"identifier","text":"isAttracting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1state\/fragments","value":[{"kind":"identifier","text":"state"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1adjustedContentInsets\/title","value":"adjustedContentInsets"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1adjustedContentInsets\/fragments","value":[{"kind":"identifier","text":"adjustedContentInsets"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1willTransition(to:with:)\/title","value":"willTransitionToTraitCollection:withTransitionCoordinator:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1willTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willTransitionToTraitCollection:withTransitionCoordinator:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForScreenEdgesDeferringSystemGestures\/title","value":"childViewControllerForScreenEdgesDeferringSystemGestures"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1childForScreenEdgesDeferringSystemGestures\/fragments","value":[{"kind":"identifier","text":"childViewControllerForScreenEdgesDeferringSystemGestures"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentMode-swift.property\/title","value":"contentMode"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentMode-swift.property\/fragments","value":[{"kind":"identifier","text":"contentMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1viewWillTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentInsetAdjustmentBehavior-swift.property\/title","value":"contentInsetAdjustmentBehavior"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1FloatingPanelController~1contentInsetAdjustmentBehavior-swift.property\/fragments","value":[{"kind":"identifier","text":"contentInsetAdjustmentBehavior"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}