{"sections":[],"metadata":{"externalID":"c:@M@FloatingPanel@objc(cs)FloatingPanelSurfaceAppearance(py)shadows","roleHeading":"Instance Property","navigatorTitle":[{"text":"shadows","kind":"identifier"}],"role":"symbol","modules":[{"name":"FloatingPanel"}],"symbolKind":"property","title":"shadows","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shadows","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:13FloatingPanel17SurfaceAppearanceC6ShadowC","text":"Shadow","kind":"typeIdentifier"},{"kind":"text","text":"]"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"An array of shadows used to create drop shadows underneath a surface view."}],"variants":[{"paths":["\/documentation\/floatingpanel\/surfaceappearance\/shadows"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/floatingpanel\/surfaceappearance\/shadows"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shadows","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance\/Shadow","kind":"typeIdentifier","text":"Shadow","preciseIdentifier":"s:13FloatingPanel17SurfaceAppearanceC6ShadowC"},{"text":"]","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance\/shadows","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance"]]},"references":{"doc://com.scenee.FloatingPanel/documentation/FloatingPanel":{"title":"FloatingPanel","type":"topic","role":"collection","abstract":[{"type":"text","text":"Create a user interface to display the related content and utilities alongside the main content."}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel","url":"\/documentation\/floatingpanel","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceAppearance/Shadow":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Shadow"}],"identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance\/Shadow","role":"symbol","title":"SurfaceAppearance.Shadow","type":"topic","abstract":[{"type":"text","text":"An object that represents information to render a shadow"}],"navigatorTitle":[{"kind":"identifier","text":"Shadow"}],"url":"\/documentation\/floatingpanel\/surfaceappearance\/shadow","kind":"symbol"},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceAppearance/shadows":{"abstract":[{"type":"text","text":"An array of shadows used to create drop shadows underneath a surface view."}],"type":"topic","kind":"symbol","url":"\/documentation\/floatingpanel\/surfaceappearance\/shadows","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance\/shadows","role":"symbol","title":"shadows","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadows"},{"text":": [","kind":"text"},{"text":"Shadow","kind":"typeIdentifier","preciseIdentifier":"s:13FloatingPanel17SurfaceAppearanceC6ShadowC"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"shadows"}]},"doc://com.scenee.FloatingPanel/documentation/FloatingPanel/SurfaceAppearance":{"role":"symbol","kind":"symbol","title":"SurfaceAppearance","url":"\/documentation\/floatingpanel\/surfaceappearance","identifier":"doc:\/\/com.scenee.FloatingPanel\/documentation\/FloatingPanel\/SurfaceAppearance","abstract":[{"type":"text","text":"An object for customizing the appearance of a surface view"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurfaceAppearance"}],"navigatorTitle":[{"text":"SurfaceAppearance","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"shadows","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"shadows","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<FloatingPanelSurfaceAppearanceShadow *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shadows"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceAppearance~1shadows\/title","value":"shadows"},{"value":[{"text":"shadows","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceAppearance~1shadows\/fragments"},{"value":"FloatingPanelSurfaceAppearance","op":"replace","path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceAppearance\/title"},{"op":"replace","value":[{"kind":"identifier","text":"FloatingPanelSurfaceAppearance"}],"path":"\/references\/doc:~1~1com.scenee.FloatingPanel~1documentation~1FloatingPanel~1SurfaceAppearance\/fragments"}]}]}